sprite $Bridge [61x21/16z] {
fT15WaKX34HH95N1zx_SHjgT_3jvUZ2tygbP6Xkd4iDzwDlcuE-BskqMsksMsgsMd3WLYmtOk2llc-PWu2Jn__4LCqO1gF7xP0RPuUNc3SE7nN_6e48eX581
2jvX1QcQViG0YHKdnqhu-9vBxOZN7PnhiE9flJFYQOEpuMEj-5WtIk9jMevraghUjixg9AFVDkSzFG4
}

