sprite $Bridge [96x33/16z] {
rTA5OeDG38LX98hb_Tzsvqx2N6_Mzczn-D0XioZeIDv3fNiU9ozZzoQFKbuyIddufJpyGlx9jp8UVYaFlvI7Nyh3ZrMxv_BCjxbxzjBdCwhm5y22LDKhV1q6
l9896-YRFfEGi38n4iB0h5WZRSqRtvvquk_wKqED9vYJyYp6XF-iRSrRl-a4dUMRlggJBuke2MRP5rDVoTgYwHj_KJNaQBcjxqUFhV3x1x-FDNxoGusVV8sV
V96VV96VV96VV96VV8tloSEFEBnlIvpyGEmXVJiQVyRXNNl18ug-lUJl
}

