sprite $Card [61x31/16z] {
bTK5WkCm38NXATZIUtAozx_j2joa3FzCsLyO_gtUSj-uRRahpUdlRnsBqKEcbMJTaqmhPFJCfvZOp5W1HAOViOq58gjRz4ZegaVw12Tp63Rr8irMe_4Rt0NQ
YQPJB-2IM7E4OqW4bOmUw0KMfMFs3O_ZdsDQvTYVF2kiniecXf223HyIlzZQYYvHPs05eQJUu_JOjpRB0oAg5umQexp5XXPrbz8YdTE0sz21QLR_TeSfjriR
4zCnN5CzLEGzrYY9HgmNx7EkaEtuOMiRlRcTztM-mP-sDk-tzk_OMDbtc9S0rxpqBGOZ1EwvhRbb6H_mFWND99fOFMpH7d2Dpe5bTxmlA5zY9pUOy0HbeHv-
m2Az2oJIznYgA5m1Z8bDDPa7VfoprreJV_O0V-g0jDwOPm7URZ3FnuYYUynd8DXpZ1JOC4G4cjCaSxA8hwo-kSCpw8nHFOEU4HRHl767VxteJ_pvZg6OiSe5
6AEmlSSwWF3c6eGgG3U9xI7UPZoVMsydQUSkNKwdKvTXhXr_x903gsKiDlnJy-zbFVpz1m
}

