sprite $Card [96x49/16z] {
lTU7jkCg38NXUsAZjaNy_czxXG6d3KxFFqtJliFAGYdBzwB_eWM0zNHBjhX7DTwIBUtP5f2v-huSyMdVZyVDFwRid_QpM3u__rck4Qm7UVNynoKwriVVUUwP
gfhCFRtZkna41bT3P3tWADDqM9elgOVYQ-hTyssUmuzp6EACFlIfj_f6FRldfnH-IXP-IfV-4ZLVkLTzxftxUYg46r-kV5ss--ycFLTLW_HmyjbBgBbBzOd2
9oe-qSX7zbxMAFlMoLUtix9A2O6A3_pdzjV2eZONglhCuJF3eCnl-HJ-sM_urfUH_z1-6GhVlkPsVf7mHS8t6VYx--NekLS-Ahxsw-3hJ-6h3lp7zakmygh5
v-wxe_oKrNAC8t-yNwOzzyqNvcpxpy_DlxjVfbiNvmSF_9VtoyuVVtOR-4_lLsvBc_tY_kZ0V_h-evsVGUVB89_shUrNtzzF--9obikdVVNpihxZEowoufET
1V0xlhMhhj8kU_79I9InVei-Vdu2QVFzjfopx_X-2gFtFzqVlJ_PzMc3xlckaPtIHtmGDUUkBvS-yF3vHVvzVjIy-8wMjEmnFvZc-QrVpq_5x_dJlaXnl-hh
xts1hO7KMepoUmjOWYo0gw6ruqUtligyPcIfJc3KWKsiJb1GctRkJ-K9LtvQ0u7QnAY3X5-dyBbEFl0nsYzLMWkVsyIeG_Xj2b_gDFQ9-XfT-iPhnMyJjqbD
skGARTF0TsnT-tLmWjJGxuwPjAduRNhszKKyGaIAcZ6yfjA6h6ZJmF_SvySV-b_zV1t-gv-lRTcjVhv-u_omFpf4V9WcdQOfpHEdwL2YlyDoSVwNiZyvq9Iq
-85BOexVb7IUbrRuBqRXXyGwqwIIaYGDFysSPasfiVAwdvQzZlKVyJhy3m
}

