sprite $Certificate [32x32/16z] {
nP955eD050HhNY_YwVlVDbzYw9R2AVepni7SzWb_4YS5o_FfTlFj9fHLM9vH-DDDMuHpnTTHvP50fxDWG9_w9aJMHwdZWsM-wjyqGiVsIHixRyAqf_GPqxXk
_hnI2xkY4SwxZqUWqfrqR_vh_w3mv__KpQ_zKpnlFopwFcqV-0l5r0ygDAtpttuyWJp-sZy9CtRQlnp_sqrRXFFEyf72xom_Ah-FyJuSp0i
}

