sprite $City [96x120/16z] {
xTdfOi8g4CNnX6LWW9dp_czxIHDpez5QBDmr_rRFjv_xFlqoes4QMG7iG3uYGyRn5a89QHG_AmAHmW_oCvX2OC0CuGcvyY4AoWZUG4CjnWJ40RuWBdfa5i1r
vnbfupahTExCUyYcfvH4aNlVDJNkV2uAXDvtpLtFrTU-pnC1-SWNKONquotqg1Ufle8xFY_m7R_wyAsEcTUrTGybv9DU0-OstrBSzvWY9-OOo3jF8NBwkWb4
uLfzDji--2MdEt_HzGC_x3l2dsYTsKzZ_BZvz5_pBz_uMl9V4Qzh-laUJv9kleTohN3jjb6x-PKFL8jKszQJTFC576jyhAUlE4UV-fT_-PT_-PSFMSCOFvLR
UOXFyvRdeRwdeRwdeRwdORwjEHhdkyk__CkdYeOG1_dhSStJ4D_Qcr_hxs_yvliHljjvgdNstQwll3NMSIz_R-V9puOw-twDrYmr-REjlVBzdz6MeoRVhPYM
O_heqwvRQl8TD2r5EiIRxvsdOzuQGqr-vGCznhBwtXXxk_ATisQUP-FFVZk_-TQQfTj3mDQ8Jduxl_dUdZlxxNmltxxWE_aMUC6t-ArygzzuvNJp6VSyBqbF
Fvwxzo__yiaOywbFptplbcZzCInZANNqtNnNY34YT_JdKrxx-MVUUEhddtaRgADVS_TLdXJ9zV7FBNvIGFoZNxhv5Bayde8fwEBJKgnbe9YT9o1pLpzo0MZZ
8pHIxEhNaeAtcxOGzVSZ2xZoLFaHVar0qmmDRtryvhDY3c1wv-D3FoQ4ek6hRtnyx4Sja7T-vhNW7dll2_ITdy9zSUydlhwxVj89R_5H2EaxFvtm5Z-39aLy
xQSJtU8pT9eS9BxoqybkyNbzlnAWyRcIjctomu6dszDdUd4ZDlf7FgFoQrOW7C-r-plF0hNJhPc1mXtyZUS2y7JCP41Icq-dLZu9aCtqa4s0Pew_Z8i2oKvF
ceC0MjBdTbfm2VFqAXi5WEJqYIq09Dhf-qp8gAdan3-bioXgcSpqeombmP9AoJanFsMhcyigGnBPgIrBCGksL5KEgIgs94Tlfu-RhQEmVm6vdrJ9YGCvEqzl
-WC
}

