sprite $City [62x78/16z] {
xTS5akiu481XMserjtp_swuSn-DiG3DIqQC_35-PQVbf47cPBbdOl5Qdu5bSWaagpE4SGiGHQKgR4RDObHdCmGsBneRZ649sg-PrVB4bjmCtlVawgDMbuMOz
ecwyz5kFfpEiAdhY5lHnAUqPSBbdeS9K2h6QHrJ-WIwNhgQdRdYJfHliJtcTr6L_WjzDhwpgsZ9jbJ6zYZTur-8ofZcOYAd5pAY3shPwjcqqhg_-ElrFXxOY
vlGHsvp6jAvhHftN6QTrphdCQyWmfV_fqZmIJkcytm5AcTCxdjTmnuW0DAWl-wtE0Fwaon7k5UnfgX6kSgJrr7XG0Enf3iAlsFTXvvnlumqvfOmzJS4N9e-c
CHy1j2ViQVh_aEFGLrsDJqCUqiz37jBv6Z9pmsCQWX-AFr9xuvhJJpGzQiYjKX3PlUBeiDDwbi1eKAzN6OVr5I2QOxfq6THauRH-uK6Dp1fURfX3U5YpMF0D
CuxhbZOE3SzfbWgc-4vlBVf6irbb8dhHjaTmzLPh3NdM7g5qnaSVTAYzQhreLxlca6Ujb-ngZRnWAF5ZmdizJTmI3RojQivF8zhN1_OeorxICE5k1RugrAXO
Q5hk5QlUzVGGYtgriZoKsSDL-BkaqN3EorC9s6kugNoKQXxL6TAdIsysZvQRwKDsVijbNRgj6GeTWpawHeWAv5Vv7m
}

