sprite $Comm [61x16/16z] {
bP07ZiKW4CLuzkJ-HzxzlKy2Lat0yXFZY0JBiKvK82vgW9eBi62Y0BdZf0PtQocSt8EWGk9K6A3gfYItl_Tm-Y2rRIhV9_VvdNcXEPGk7BIsify4kU1B2D0g
ENf3Rsu6g180vNjh7_O-7vfW5xvhscjz60KobZ20ch6E9JaM_m4
}

