sprite $Comm [96x25/16z] {
jSw7TGD13CHGaeDPgV-6dMqwwU8U2lWFSR02ZxYa1AnCyWhQ9jzZBgqtkdDCIs0gVrJCexERk2y3-Q3IkUlVjB37ZFq2g8YFJMm0b15kNdM2ZaZ19_iLTNm_
1LQpyKzkdjn1uzlzzfXj_iW-mzIsZRtxXGUnDMV78Yk0SRyFLsokQDwFMQ0AeEdT-yM_R4P4QYVTJFjkrbQ-5P40YeCvks6ZpAxfewdoGG8JP_E_j86C2L6p
wSVxmcvwAYyRAcQND7r5umpz3
}

