sprite $Comm__tower [62x211/16z] {
n9Q7kgGW38L982Gqp_k_xIeETzo-P5jk6Kl-R-3tg8GV5PV2mLqPo7vQWEQd8z39JNF7Y6wQ2f22k_HtjHNwJze8G7IYvzy0nCLMA0K3p4CpW4m2LE-KOUb0
Oz_8psfmfaqnowbD5gskf0mS0t1gumOakt3ou1KGCc_QxgJeAEJKraCW9kyDXj-umJhmUyyb-Mf0EJttIYccMLACJ6SzE_DNIM7h6FpQrX8R7dMqQlBzvnBh
J0z_R3Szy7aT_4nRvmVRPuDzR1zACKbMgttHWxwfZUJLqMEWtEQMF5hJ79Ozx-Qsj54USrm0b7EVwN-mWUQn8VIDnpb9dQFA1g2yjlcfljvpIf6PFzIp6GTA
zpWpqsoQs_HbfjUyUwl5tkfZEQv-vH3ak5dZhzxKptfV5mwtN7v918RorxcQvakfjRL-6UgptumAXiML-xdz_I9YZZ4bcKtSEtDQ_TnHujvTzcmdtht3bptl
qyLTxNTMFTIFm__wvj7QO2-TZZ6EvALpCslPE_1YgkPTgQhfMQO-usfPDPkwh4SjeYf5eykusaMRkgnBlkdiYde-qVcRNSeNhHxbPlcYivb3EckHYvQYxBfW
YuuEvMetRIeEvKLlMej3EcDzDpppHj4hvrhWcJU4f5OXWMFUUWqunciAZhWKq7oF1K9nBCzhkEbGAsqhxxfexTlI4sJHWhGTbYCkEXxRSR76Y-PcktIlj6Yg
VOzTbubvNRpDdEgRrisiBi_Co_zkJXVjoAeDUjCqR3EdvKcNlQpoqF2cWmxUowabNZH9sSjg7ebIuekcT6wEhQoMpdFrANAormstfMqqchf4xiysFbLg9jYn
wo0GRGhmB6l_g_sJc_UxqiZ1VlDmJyNaIaOu3s29SoyGHr9vx6dGuMhTKwR3rRgdGJzrLPP3c9PZaMUU1iskrZqDkkugrmYWEbRtKwAVxQlhESdFx7CjUth0
xNDzgskhkYhdzW_d5hGv_d7rb1gjvtmj4HD0pAzzzTIddley-rDNf_3qUlg7grFHqrt-C8ZVoLvpLVOrezUzGFDw0cZTbJrbkkxgr3MZjLQsjIEZqTTIqSvN
HhzwfMmuzfH6gxHEsXPN-Kd3TMvQynIkH8khr5oTcbvP4hIOIN63aAlLUlD0iBN6Iuv_FGrUpGn_N3taYQSlp7EmDLUvDW3Ni-vfq6LNmrEcwwxArbuZ-jKs
kQUnhsDwtV6RfrD2aqZtdevf_ytLkStZgisfgtnhwiXek59HaalQlvu6polqNrURt7jwhOJWWM3VypRKF5NNeE4g8Q9LF0qUYDoAg_oXgK-Jgz2DvLo-XCr6
Yv-lVFi0aZFU-Ba_tTFJgKLFcIxq0FEXzxIsUKnlkzpJicz3MCuTzpJsKyQUhkOOqp1RE-uy5NNajBW9kPfx6lb4murS7NfwvHCjhZ9sbLluo0yQPi8DrRsd
aGz4xjZLVFs9ELJX9abj2fwApRD9qLLgBQXFhRYwNvucjf2hUmfBtryvpHbTnljfJhCKkQTJZRRSKofmIekvvwxE3MB1vxGwug2OUdhnH1CRXrI-OhP0FD68
bRCS67ZAF3y5sTNSK-O1OiUkBgToSILek0aVzX9FhsSpvmClsC-rq_RakNyaxmhDhbowZkz-5TaKJAP9ikaPlZmzFNC_SzfFI_RJAgrzIZmjqechiXqkDLhy
sEIhQ72hx2tgYBBnlH2Vq-QW6f6dmHDDkUGgxpSNppJdnW2Du1Y_HJxHb1l3EzvdmrFEHn1lDbpblLiF_bY-fZKOzJViAVC0vPAhzvw2fZL3L-cr1FFJH2oz
qE1XNdQPZVg4IkyB57ffVKZpVDNxx2fb6ZvtvxEnkjPek0cvUhtIKCvdcZsKljBxADhrXpGYODiayLIPPrfT4rTflL8-mBcq7z1v8UC1ogKp2FT_p3CDOhcl
tAC4p0VDkL7eFNwNcHRJ6cB9LKcsAIwnAh6Pg-CvYksxZSyHWrSAV0uTqVDxiRO9AQilZFntRwkyjuQO5X2Bg3b-yk8crmOHZqJY8v2x7cw9vlRvN97WHtC7
QeUYrZ632IfoYGu-s9ZhyFn79vjkvYsVRGoEDMPF9TfSNMcUHNClTSJFwLEGb-dQ9Job-qsgfixr2ycy6x79j8R_CVAjUxpV_n8YiONuQtufom5YAPzDPHx7
8h8TD1FZV7VQfOcVZqsmzzLaE0GPZZZ4rhxZXULeGnuOiktzvNkwd7sr9xGj_LpqunxED1_8SzlC-_FI-s93cdFxbKlytCxDv9uMsywFNCu_pzNkQ5tQkJ3B
-Nqt-QGfjrDkmdzy_fZMjJNA7UPl9aoBhftOuVNf3_1csr5Z__T7thIj_IopuS-_-O0OvJxAdoPoybb-w_GvUfp_I-xV
}

