sprite $Comm__tower [96x327/16z] {
x9Y7hkig54GDU3UAv___zedueY0ht7ROhwzJLBD0di41Zb_YBEKy_4W0aFpytFtYvwVkByxF1y7D7z29Xnkj-nqRf7z6mFMV7d1o3fYS0rRdWDl_0NymfzUi
grF01BG-RHa1kpmNju0ZlWqGVG8Ek3cz0cvZWE8JiE8RpITWmipbi707lW43JW5NpF1sltHj7QEOJy0j5jmuhU0G2bv4hpTGA3x-yMQ-1sZ19-2-S8EYn6Cx
vrYuJiH_-jwgZ8NhXFneuQQFgOSGVY5W72keFRyNkZXaTAgfC9qfnlLeyNiBwwpFU083EIW-K4oPpkF9Ek1KS7DEzevMBB6d9Iy2JXc3E3siJXMiUKwLFuuQ
3HZe_B0w4knd_Ek0es8mfdyM32pqb6DA9x5eRfWfFmuu26RaZcAGFsILwZJsan7XdE5CdACedvf05sxQq2m3dkq57PcYgFtpwwWqBEytU6u8Pc_5eD7tzr3y
UP652xZ2AyEtNUDpStJH-lRbJSltaaunl0SW2e-6zBWDRvQJEouiU8GHygCX2HCIrk_VDVE7xDaGm_ombgGVB-MW6evdGzB3lYGIiLhvplm9eCCU3Q4HHJf-
aX1Yl9UqrLSXplSfG8-GR_lW757y9Y4SWtQVxHuH6h3dsZ8iTX0nRjoYnCEDq_dwJPolttBtPpy_NdZkG5q3Ja0fZbjG0im0ShpSkov07IydSmQQtm60LTdj
Z75UXLIfEAtWsB9rl-NcqT1GsRJxrRW6X-aRPUb-oMGUnrEbnjtFZTGX0HPkrFtKM7Y_trZoxS_2jjz_TVVuknpgGoQtNungSAXFvTlFbImwr0Tq-maE1MBX
Clp5eK36OiDl3WMwo7JurUZQNvyYmozvUu6YKUFXvxQzGAToe-6dnhiBn2BvxSyYlBi-jtdytrsWAYPllvZKpVbUuBUVSSNjUuVsxcS3TlSJQDbklvK6xEud
e0TLKPNAXsu_PSXhsnbpQpc-DgAo_MIHNkEylEaFrkmZkM4O280Wmph__xrEWgfPF8zlJiC4TMc5VCfupeqpppaodoms_IsUCjoG6RUhdInUh_tNTigm86Si
rtQoEFGVBxTuQs7NzuDk-ImlPvQduG9ok_K9qUcWJuXM1tr2L3he4wBKGPyGfGxwfH1qq2T4gOD-AGGTz0bHwg3lXwKE-eGeTT0lXQ23FY5A7VHh8HuVxElR
LyjqcC-tuzhVtxw648KEv-C8CwlU2467TOIPLIT4eyCwmk_Nvra9GGVxo7OL2P7fOFtuHQU3FY4w7VHR8UYWRs5rEkYtGdYA-k5xY4D4tw6FHeTxtwshTBZt
2L7fe7zTkgKE-eH8TT3tor87VKAKEjpxFwsSYMxZLXJ58Fl8YwHC__zlYyGuW06cR78rnTBD8RNSHxzOng0GaphSm9T23EhmiIx_mSzngX1TekjnMxxXN_Tx
K8XP7MfuusU_Nr28UHrgI4fVM8Xv7MfuyVEIiH3pEjIGl4HIY54TQjYsOrtE5K83SBylye9n7JZ_yq9eW1FBzsJluFnv8J3Uu9_VG_3k9Po0StLG_g0GVlA9
NC997OG_AuGFNo8ZFAu3-VD2-E9Fv4MZEf3FanpNOLD-lz2PSHssFShFiTuwPACwBBSzuB-zmo_ZGhGEDO1_sUvB2t6Y3ZNWyut71OKOrg66zyytjYiASQOE
DIIlVxbA8IPrgE6Jlnwh569MXtxeiwuf7OKuKuSQyEtTGI7iiDOU_7WFuPSraHirt3kGpq6RrK7uM2YJEWWV2trO1-UZ48CwEDyBuNLm_h0GFdI9ZFAu3ixt
GdWTd3ylnAKpuNn_iTVX-NnSb5_wu_dyII4u4XSQ4jAlKWYl0mq9w5e8hmCD2UXQ2Ay33GdeMWYl0mq9w5e8hmCD2UXQ2Ay33GdeMWYl0mq9w2Z4k0xNv-D-
BtrG21uE3Q0FzX1oEPEVvzphuFpv7iB7ET45CzyxEDyBuIzs_g0GThA9ND917PG_AeGFMo8ZFQY3yNr9UXtklvoVvOwPqpfSTnY4lzpsyAIz3ZKultGln7UZ
K0FvfClGwIZJa91kYyRhG4C2kYvwhmCD2UXQ2Ay33GdeMWYl0mq9w5e8hmCD2UXQ2Ay33GdeMWZV2j2Gb3xRG_XXPD_tqgTx2B-CjziWwpu6tWSTFA-3yttX
U1r6V2-4lyZvBCJu99FPfULDShwFXjTX7VANpGlHEdnGuFmMxzQbwNMuhCVwQ_wwh--5y3eiD3X_FLOKGke0W_3xF1k5a1600No46yDd8qm3-QLlfMFno1A4
WVpIBxhulGuq9FYTMmgXTQ21dsze8RGED9HV-aQI5u83HaFIHmrN6s_VEuYXpryYotEoTwWXUQLW082U1JkotYHEMWY_V3Ny-MDqBmHll_V11z3hu7nVG5w7
CPy1yF_fV3z4Fxavto_nYl4HlkmFvFzjstN6Rwy_zn1M1tGBVAC_BbYYMDngI9HUYDL13OdHMGZMmGs9qLa8ri4DYT5P28wk6nAZSn5nwRaXCJeZmF_XXaJf
FKofWniIqFKoCzrkI43NCU5RZniIfNVCvQtJ3OdIkqpbhTyD2UWAejOD2UXw8NZPtF1uWAutahVT3S-dqpk8EhQ3_cCXUHtcV8R0i-5y2HbFwkCl7VzoV5vg
tXGP3UDpdxrzZWg72gCjVA6lIqUTYw86vpkzIvMBMjDIljDH2DJ13OdH-MiMw-26nEWi1Ej00_caxoiA8NMWmP-_7AiK0alE38dG6GElGmt-_6MLGaZoO93d
Bn9Zt10t94Rdk72Wt90OdUFkUmSQ4g5ZkR8ERYX_kGiTGEZ4a3WTXS3bSaDYTDvGtcut7CSsU8WcUmVyOSPIRomeB3UdtxVhklOZIVyh3KBhS5j-G7_Ttnfq
ezT3xidaKCFoHN_nQU1hUydVRWOCe9SlXdwqs95v6oOOG2yV1ZIf8_zU1nX8Bv-6qezmoNOnqr0w-JJqAGEWLS5GElWmbCv2i0urb4u-3VqP5e9rwB5SIYUV
XhLq5kBxEbp__BCjF__-xVwyV5-8re4pqpDsVf-GS9QwPUW_S6PgK7x1DBm6g2T2UWtayma93BtilH6Wqr0-wJHqR3f8eCDWprzewDYt3g3JuCzVQEYoxK8k
tGs97qeD1LVJ7r13-NsweuOMulColTFTaBnlhTpmUME_RlFkzFTgt6vDyFyRzg_1VEBRQ6RuC3g_iVRy6dyp-Ffr-ci1N3SpED_flUmr_AtF7svlT1W6VAUx
mVbE7nYI0TqCpdUw6vplzB4XcT9fCBxJvuRaBDqDYT9F6nAXpmmB-48_QqYCVjwG6Fsy8J7wUKDYzFE6nEZd3OdHpnkUJwMVDpZzlC7fvms_fVyB
}

