sprite $Fax [62x41/16z] {
dT07UYiX34LX95qLfkJjVxVF26n2slYRavxmpoKkFqRwG-NTcEbRkALvf3Iwr2JqcUSJmaSsAoDeowJqy5txuBCuIq-K7y6LIsOqx-5R5i8jUiNwr9Q_DRNQ
dxhBrFk_p1MFfDUEmuOMRLWSldicU8tBH-A3JATkovPwJaEzFc-5Ceh47rhOKWyCIxrCktKCg7JCbY6FISQvtFMShkvL-h8AbBkUaIWcJZsdQztSEhPsgbsU
UlarJsBWhkUqXzUDEyuh0YeFiqG0SyT3SmvAA1HFp9dWU-RDJUtKCgUC0QPFyRSMBTgdyJnDVyQwwFolsILeTe6d5ijfGuM-aoqwq39O14FM7K001RrYjqMp
QSl5eyqlMXHjJAWqoCAa2_QJHSRhk35Mp0yADKlAqWwkqrijYfPxsDUBGtDRkWM4TCL1fRe-YgYYIakM6iC2p0lsdGhso7QZBy5CeH2MXbNnPJfgATNokUhy
LJzGayIlV9a-KCePtehmos9PFgIKSY1JaylyCzvH7ftRUExxEh6KbXqry_Vrn8KZspQygIUUuNsT-BQE0-MsZftBNPtNlgjp-QxEvTjwBg_9SOHVLEl0twCj
xEzqNLwxr0l-fi-BViB_0G
}

