sprite $Fax [96x64/16z] {
rT07rl8u38LXgrsv96J_knr85Vu9No7JNihfZ-zH-Zh9_gQSFisOteIFVT3_qp-_Z-XHbX3znXUbDsL_b_tgGFoOoZ9NndTDqP6XheskwSYfZ_dnDsV6Q_Hd
_kGtfYMjd9_yr2NroEaqpT6NigqhBDdI5etQ-vZscgizKWdnmkF9RxJFDwctOUlMlFVpuRj0_cZben_dYyB7kbOoGJf_sFcHgEYZLtpqutoMYe52-PctQG-9
BOVp13xu_VNXJxwvHPwE-INTyu17FlhzVA-1XxW4tzjMIND5UzxG-NhCXpxcS-1L97CwZxFsVF3x-GEUvXjCH7H_WAIFmWFXEC6FypqtXFa6o2FDciwZh96F
VZ-_rT6z1jva2KufSLYTvD4gk8VZzBxcRNvr1yQ13nwofTafdSOPaOz-d5zpphK4NkL8tS7fB8OR6te_pYyGEZB0bBlCyvig_l3Z_E9Fl0dzB4FldyytPVer
7_qu_o25wGC--64-Qw7G1tpmmtoHyG8--d5-PK4JU2pxTujyz1klQH6jkO1EKrLM5J5ZwijuxLl5scC-C12v6xrAb4rP3EPCAT4ItoE2d_YEhInQaIjPQqgl
CbE5cXdipgSL5v4ul_T1Mou0HYPHUJqV1bCp81C5NKxdOnoJYKBcyZ9V0APNkTqJu34_wAfXVizJ8fUriinNrPFvyterOC5NNINEx_cK6cmfDvHAOlPwFbHD
oKp4mdPLEvi_p3nD5MlZOpvWz2hE3WFK0QQWs-dy6zAzSclPb_AjqcamWucPg57GpSwlZta-kBQrWUaiSG1c2WCllkYZy_bradb-C42_Ah_cBTsRMjbhvLTL
F-VJ1Dahyglo6N-z7_dLRz2j-faVUKrhRHhhrd257_b7jugjA_RtV1gd8_l4ZtoCzoPyxaU-xrC_yjVxaR_UZ_prVkIlzq_ug_qM-Clzo5_lH_vwl-ElzoD_
lLy2_zwVfY7_kDBklAHln587_3H5nx-h_CBl-Clz7_2fZFcd_OHFUVfnj_VyNm
}

