sprite $Firewall [62x111/16z] {
fTO9RkGw30JGdysY92xtl-rdKo10nov3q-7i3J_Kn2WKyj_s3RiSxzeFCjDVPxQVBDyVv_jIsqw-ufzTtM_mSUpfZnlyVHp3zCtady37MycV2_zi9DDVaiTj
SlzBiaVt3NoR79hUAadWDZTq1ybjGt_q--H6EnfXwLW_byIlQszTiSR9VYvxLwYVavlheJmVDQ5arwPCZtgWPBzXJ0reM9B4NHq3ZPCh1del6MfSprOmr1y0
qqYCDIu9ymihBKoSUgyahXqB9NQzNq_NNNcw3goUlP_iMfJ9zS9z6ktNqtKqp7LWAdgt9A69hTTtlbyIruurzTQ69GxDEelUJmxDsdjgc9oOg68tBY_w0tLR
g69YXw6fQ5YIhkGFswYubLLyBedhhgAZuD13K-EIn8FANKTY2brMyR4aNOs9N6ToQBD9gM5o3g3hajmeLt6h9A69ZTkwePDQQhFZwtpV9npQatLfEg-YQQgY
2mxDsfbBygDk5RjMxHIQ5gxQ_tvyLzrcujIzjT0BL_qwfPzrxV3Vffm7q75eJvRyK9PkOmonSSHrUyMwTkowbWIl8ltMNNaebUIN7Zfp5KKOQrMcq9aCLl6g
Sm1TPtASsCnL5AK6TRpjqCIMzQohgBqXlN1enqQbdg4z-K47Nffr6fNab-ui0skEvqB70599Vcd9LQnwjaNCcFAl_b1egWsJtgxQT9t9hm4yhwAKLQpP53Ti
5XpQasqazkJGD53N4jFIddotYW9qFfS3E2dqAidwSEgSI0VE1nMi8jArdiDchc8cDuSJTuquNpnTLZ7d1MfF5Ydr3Et9meaz6MhMFgM4lFHawSpbGwHLUtEz
aiigjhAA5oqpZYrQAFKvrnAhM3yaFcbUPvDSmrKqeNpl-WrthGqLfLfFrvuiInCdVcCLFTb-dC5Ld1Iwb8JLPdEToKZJtIfIhk8hMJqPwNYnePquBYLnJHmO
QAghg4Q9SnNZRKCTp-Kg3gMANKSor1BFXMQ9LJmth2PVbydcmofIIQvQSnMPweQvTcm5b-IzLJGRMSzJCbx5g6JeeLC7JdvUnPchM9EnhlLqxH-4Xibu5IbN
CP8Bnfh4v5HFr_2_VLr54KcSgnZ96vhlLb4YUKERn2eMx1ecdtTDRbOHVitNJSrTes6AwfctiOeu6UjXSuJ6oLXRhY9EVbh5cT_j0OmrvIeIh2VM2uUUA7bd
5M7opYeQJiQhY3SCQokhk5SIl4mWUKE3v4qDaZSrIDxK06zgKCzD3PBtj8BaFLsIztKUJiPtfFtdvFy1
}

