sprite $Firewall [96x172/16z] {
xTW7ZXqt40PXXTtbHFB-jpMwdCeGdz6YUvmBWOWVddv0ZP4-_T6-za7pjWTvAkJhVVZ-zRDoN_2Vup_md-Fn7-Jjr_Fow_cFwC9_bFzubcz_2Vy_Vpx7Kt-K
n__y8D_md-Fn7-Jnd-Fjr_Fsw_dTVZr_dlBh-MtWRmE_d6y7_dRZr_FuyFZvlgHu_E3lZb_DumU_uPVp-C4t_6eUVmIFNytZmyklvRSRtduzB_yXtduzRx-U
jr_Fsw_XCSNBh-3FOyRZL_3xE6Oyzx-0RsVumO_3_1L-0OyFZozU_ZgFppYd_MlqBd-TnsVxyCLlzjTv_E3ZDT_ah_Fu8tXyyVBNUNnuVFFu1VpMuV7DunVU
77puSJRvHJm-lFqw7fznJlbrF3xR7_BhUFpWc_qo7hy7_yhFy-SctZxyIpz_xr7Dqnsy_64_pxSh_E37RfxjvP_XB_3uyFB5uyFBp_FuZ7F95uyFBp_FuxEz
VF7umUzTVfh7seDl-EBb1z_ivtcmuF75o-_1sy_pQF3uukN3uo_VU_dmweINltOKy7d6CU7jtoiyFhnyyVB76EzVvxszlU3n6UV2Dp_nmQQzuF7P_fGlFktF
UVpWctpnQN_Euz_1uq_ul7-Qjm-FBtxk7z7-FlEFqLxVU_dmQjWVTBrzM-lX1p-swRt7Xp-QEl3f_jdl7qJtm6tuyFB5uyFB3nwVFWEsbpxyVSiN7pxy9Jzu
VFNvfG-_oHUFp_RnYZzwseTl-EBb1n-l-PRtuV75ox-3nnV_7JuyldZvyFZY4xxklNnuTS7ZYy_wRD_amyqECZxysPA-UNnuNXAF3v_tpUCp3Y-PnuU_qhvv
VBQ_v8iFd-sFj6yUF_Y6Brv-y2tlmyk7nnSl_mx-Etnu-V3uukN3_vu_Bg8RNdLuVF7oWvS_9hxgitil7qwnlVnzulVVpZ7ZyNKLI3m-VE8-JtXy-5k-U7pu
j6yUd-ql-UB33_xiUHzUVl0DNxpyu5lUXvT_1OylNluLVDw7jm-FBru-VDg7LpSyldZvy3aVPdpxpmVvS8hjipxycFBuyEEOy4cV_yUSyVZmDxxvh0-_oHUF
p_OdllYq3z_mnSiFlk6Bp_lm-EBbdy7Zcy_xyFZYvGSlt_pS7mVH3IyVtZuy_epVClTVFlpi8EF3N-Rx60FN_axaxsUKCROPZm_FQ_uDD_5z3j_bYmyVliiN
d_3Xzrl-7hpys3xU2P_muHk-UFd1DtppQHyUNxpyCtXyytaV7b_RouV75v_tuV75ouV75v_s6KS-_EGWuulF-ERnuNX9FBxuf0yl__3V0_FuuZE-UVpWZak-
-F35ftnu-S4t-UB3FyLdV7ZvH_3uukKF-BmFBnyUtxpzEJ-_d_3suV5d_2RUsNTzVk_nPtmtx-oVHFh-X0jU_iuVRyRdzv_zUdpuBb_yWkzVZyyu5xxvPHzU
FjlZcr_suUKVmUERN_OFUFdm-EAN_HrUFZo--6L_dzzxVF5hFjoOyVZYLtmu-URnnQ_uS4SVCnvV_8eFt-IB3_yGl-B3uukNBtx9XySNBrzyqlUvXvUVlFVv
-m-FdxZtEVyYylUjldloVFxx45w--18V_hpnpLVvy0tVV9aFZs--peV75r_dm-EBB_Ft0Oyllig79tpuzqyrldbyyHM-UNpn9VuMl7pn5JwyVF4bFhny-4hV
_9Rby_VVlBTVzxiQOyPNxZFdwttpzRxvUjzylM--tZV_b6--tZTVxuj_n1V_Y2_-4L_y8xxvUh-MntV5F7uzxuunN7-hWdy
}

