sprite $Keyboard [96x22/16z] {
jT87clCm28HXXW6aLEv_sdGP_NLt_TXlAhRqfSeYSWVNwfzFiRb3oe1qFFHMq4g7JuFQD1WAoVUTaWgqwlSh7hp5qCWQmj2Yp4D3KNTxtz5TWLxzQuUgqXQS
1rFzrm3en-TPZQZl9rBPOeNwB1sCIGTO_Ui1RYi4r9UdOHC7VEctL5tLTnbH9-T2G1YZhzd4kKB0wnyGBEQ2MFhdYz1Mv9rId9Dup4k_fyAvWWa_83GMLs6C
VgIBwrluY-aVwB-VeebJNnngMeoY4T7p92AMNMoianTIP_CfO-MNmNxDau8fVvZMlHfZSQbJh4Xjqz_VFNpauv6dsyjeXFtXprEAPX-_xT3ftVVisDhdkp_A
GvxwvawLb-pSNA_yFltAxzC_B7d9OzlSAGyoN7C7bPSx
}

