sprite $Keyboard [61x14/16z] {
dOy55W8n34GRcnhb_hT5CZpS_qhqhvGarkOFjfH7gA8cY4eSjn6cYRjPdhxIjIcYGSmPtOAS1qBCD4ynogrwVCJEpoR2D-kqy0-4CfutJN2KPOHzmisek14N
hqSPG_sZh4cvgd6KOwYfwjKEOSEOSoK3QmtCNdnomOu_ODUod1idoUpiIc1qmJnDv23VkqM9s3aGlhUiXj-fEBXoaCD-1pNTiX2_KsShHxRh7vgal0S
}

