sprite $Laptop [61x32/16z] {
ZP87OiGm20JZ9bX0plz_6xWkHv3CzJ9QYh_ceF_DUSxTpUWt_0aH2Szb0MthkWLxS0GjU1o3rjZMgRjRE_nbSLRdUSRp1DTnDCs3rqebK2DRiewFH7rNdNKC
xzXDPnBAZdXmtd5xc5CLY61AEzvBLJY2qnqN9aGa3mRpNgfQZffALQNi-4XDKOTRoqVDfMgIxrYOqtf3DIixvfVAmMUeqwjWC8sXezfxTN4HbshNQjHuMA6z
6mqpE3kNEsQwm0EK1kFq26LdVeIQatIyneAfXyXj7MWK6FaVzfcwaDsGHta3n86OsMcJL78BKaC45PkaXeeAOO9Olyehkoeg9V1KbxNZMZ2rZnKn0gQ1Q0ak
sx5SrG68gc2SrrtjUWmbzwxNUZMuV1EggQSEd0BKC4FqdJh8YAKoY203Zn5BP8hPGntvFl-3kJhX1m
}

