sprite $Laptop [96x50/16z] {
jP075fqm30H_jIt9vVwtZLc3qoWhyZA_5uPX7mJFTflA-BMccpIZyYL4Dw4ZxKNbXo2VmNSZR4nXcaX7lo66okI_cWHvRjS2Nk0z-FN4yvJw_GJXy-EG_st_
xDfZqj3xgrBv2Vap7VoLFkt0-FKD-Umm8FNy3f__ueO1gUFCJ_mmQK6y-VGmGDRy9vlF3WD4lFblTXZ8nPqFEpKCK6y-FmpisP5VUZu_Z6Z7HhxG-Vmmm96V
UxxGmm1pvkk76cRQpPlF3sCBcSz_B_bVUXYGlVdyCB1xy_bXOEz97MNpe_33WEBC3-mme1HlFZyCxDvyUXZOtVbA3mDgHL1BR7uCx32mLqV-SgbP0R197apn
j7lp_JZogu0OMA8Ca7z9ROEYAnBtqOrvnCD1pc7ZiS-SiGXjVQQwukglWsjxgwOhZlrreTHsRTSGr8dbfSIoMcFi9ZxC8kpm_pzxgoV-fxGg_s2NN4sqjbEx
5VCnxGjQMlqSs_T9A-60Q5cc_RjdVvtPBIyKE_37o_QNmdw032xjjHNO_wQraczIiapx-t50CxcBsgMTzoT9O7o8SVLhWVtC7s8C4hxVY2TN_taxQDdkac6_
eBRRm7x53m
}

