sprite $Mainframe [96x126/16z] {
xThdWfim3C1nUGGiURt_szQp9dMkAw9J_xjiysFp2TWpYQ_yYdyehan-nMkk3EQTFnXvp3jlsCBDv-GjRZull_aguVaozr7O7hDpLDySkFicsj5ZTiosUM7D
8peQyb5xr5mHSFbdcjtYd_6OsidlB_uUl_2hDtrtzEZYPo8izTsFR_e0IcjZddoilxOri_PTNwcYMtkRNnQ-JkkVVIGQMuZUyt7y_8NlLzp7p_s--BwVF6iM
p7xmDMfXYvYNltPT1yVj4_PSZTztj1OVaNt_EaUkNLwCCTgn-rHyyXxxQCI7PVRFaqhO1o5QVXz7hcRDoUn_Fd5jpJ3xVYty27_1zKTyySKNNtpnm-p_ySKN
NtpnnHTVVF755r_yy0_wueT_snS_plu6NtpnnHTVVF755rzyHEn33kJsWz_kJ-FqeuSx_PW0Sigbr0kiVimUGDdgwvQDd7vCyOHI-SBUSFzgyB2QVXUNkT35
pgZaYT2tu-zw_nMMsSIT1nLZBgNuGUbQBgsNopJjgqZmiZe33TzJA2CDGCNWALrvc7q2
}

