sprite $Mainframe [62x81/16z] {
xTW5OgKm483X0EFO_M-xa-1R7Ufj_kVoFS4XdK8BDfwnjB5WEECkXb777PDqiL0FZKRuI7HjVzhFMdJRvGm1Be1BigHggYhibSzWG2swCos1T_4dhRik-D1W
j8XRUb0HzkJLslyfoAf7nqG8V5Fdf-Nrtyteh-YcjL-A_U_FrpkFQykf9rvOwqwPEAwzyijPyPvMpY_VqY9cMfu3Ykion3t4gDu76UT8VjgqLdNLG-wlwk6c
7jvFLrrrrLLNFUP-eQwwwgeblo2YDxJr-v63i7RS3kCqcjU7jKsI6bPEAJKQrTPJcxPKzdJBrdflyCknzsv-Rj9Hn_Cii8RNQ9eDXtd29K2R9ohu7m
}

