sprite $Mini_computer [62x85/16z] {
xTQ7bkCm28NXIC15bbFU_sqNu_IAsBuxtxJJ_dCdIh4tHsK-ZDkVuhwLOUrmMjvI6KN7klGv4VjsTXdmkivpAlQwzDooroMvx7LkMOxrTYSy33ZMXoQZL2-r
qYZSrZpYeHP8t6FDOKzgD7LOoOfb1QUhzgJMtgT5Qo1JJJ5rGOONOe1ds_FS-zmLcgfjjVVUajjDrMhLLAtDgQgCrw8uanDcEODRAdseWnWWzvVNNpN70Cpy
f4QCLSB9RO6o-OVEN3G2QAhubnutImXKHFXxQlx_JWsNKyk_l_-HK_l-JoQg4GpuzVXFgZb403R1rnhV2R_7wfrYrl-yKgRsM2bR4woMR2rUYt2chZ3AP7Ar
04mrMOi0bAt5QvSvDQzPE5NJKkTVBPIl5mHvMhCOVikYb_TC8VAYfbe2259AJTVogevWyDsfJV7h66ltFvUwxLjucooztUxRudM9uBjJQxjfizQ9Cs_xQRE9
dzhjQysMorepOXe0NcgFDyQtXw_-lcnILs2FlPwxIWXKnUcq79YR-cxROhIj-jwNLzthE5y-cmw3hfQ_0G
}

