sprite $Mini_computer [96x132/16z] {
xTY9igCW58JX29m6r97tVzifqjdtA3qh_xtPawyiTzbT5KlZvbj-QLefDtmOMkQM8kL1NyRJb_7qXJnzyek0fo_YwUju-ZgUlewdh-FfwtZwEfv-ATFOiWat
_kARjihlVjoUlVJzvk9BtstkfJ-DX_B3qhxyiF5GUkKdm5XWdZasx7FCiy2C0M_yQMGiD_VFT8mn2VnfciPwbm54WPyP4_W0edBwwsm_pt_f-YEOF-hrFzw7
vrrzBIO-YlRFd7Bst_dTxtxtkn_M1oG-UUN7j3eWfvhrvQlokn_pwW0-zlLJvdSVSNL0ZhMWtl__lykt-uODPTJ2ItzzGBAQQlsqBVDVxtTVlt_Jxv-zMvqX
kPh_x_pk__xhB_UquT1v-lz6tnkGlCptLSdcHRwpgYGpaHy0-bxZsz6tb49xtm4mxlyzQ-lx2zzfVFirlfVwbLVu3hRtlT0Fz86WsBvEVWWAtz7NxT-2s7SX
G7jyyVWJZb_1djJa_5P_VUV4vpzkM9qX3RM_r7SXHA7ll9dvz_xQl8tPxCdodSjyy95M5coU0_RFxlofpCFM-HFCWjdZ-JCNlzlgEmFW7lfnAMudMZ_9ZpkP
JrxcavVvv6kQwo_oDSNu1dac63yaB_F9otpoPx_ad493d_pPh_sODfJJE9sQP_AdF93BY5P5ybU1leIdNvP65VBN-TAkV8l_1
}

