sprite $Modem [62x26/16z] {
bOq5aWGX30096a7-_zixoEuKwwH7qAvs3_WwBBH7MJhJEMqybdk6SuACXx9DphiDrIYhVPMBITvja64hxxQzVDdsSjfjUtcpWOT9JhjjB-ys3qxdnFHWvqu6
cV6IUOXpqZmS4-YIQOXtQHHG_5TWaN6JmO6q08kO9hcKdChyBQvPr00zb5tgvLREayB2PVto14L8Pzekk9UTgzshdPQCHAY_-xAisMDQo_-q5fH2tyXX4lak
roMxF326IIB-0iLbOtcG7TIgTYpyZH9NWgVSLRx5W-hf6_4MnwkyWDPYE2RHVpauHUF2vxHHmMr07HOUody
}

