sprite $Modem [96x40/16z] {
hT05aiCm40NHZHXYwVwttQ1KwQ3AlnTDBpF-UrreNL9vmtTLx_Wj2gh39z_iONysmnVp0RwQXw_cN_fUniDNy_3LF7mr3r_DmrVpyDKyV3KFNyt3L_FmzJnz
FK_VzjvJt9yFg5xzgk6tz3p-yJf-KhoSxPblvZ9-CmA_v1UyV7po7D_OfGp79y_nVRWLqwaOGZeNHZZa-EGvlXrygRNcarTFJJ0-7bgCJvxZctd76OhtZncT
3qky7tcEJvxZkp5dFfLkVuV7GxvzygTwhsOMrpAZzf8_TJhmTXJBKlF9dCdVElHUfk_oaf_TU70Z_tg1K9QAN80y5x2fB8K5mBzOm2tsi01uBB0lju770hlB
-SOpq_inxI-toNC1IODdXwRXjnVyFm
}

