sprite $Mouse [62x52/16z] {
fTC7Wfj038LXlQAHO7t_wsw1z32U17_Ro-zdKs96nNY1kbA8s-XHMzT8YuWx058vgYiPzq6Z5IzWlPIhuXO0z2Z7Vw6SEQe_ZVyzV_dzT25kg4Qym5qYuYum
UwkHukq7WPoZghUjnWiNBIYFxXfct0PbRKDuxR9tB52IyukbFruondZwwDNRf-xZq_bz6V6TUxRfVkoL5a6dYI-ainwFFGbGxkBbgdlh90byjI8EHs9o7_Lf
UDA-xIcSz6lh52BGY1dalbUUx2oBvBcR0k9fpTujVYV9TcQAJE4qhJ7s9Fx0JwwVlsTDujv4NA2D7uRZYlP1N64IFsYxZj-IwnXrEUqtOnspylff_riyBkDN
bhadRyVeGLoobd6CdiHABcFjchxerG4Bx8bhrd8viZcT_cws7DoyZ3LRdayhbyk1Xt0jnPCwOyBpLxrS3lJyW2-NWs-BQLN6r6ZCwjNof-czPI-MZtheMTmZ
djbfywzMgVNoKSTVlT84rij77M1Quaa-Mk0yOElwgvVipBGjud0iBxZvDtqQxLZpVcapOkq3
}

