sprite $Mouse [96x80/16z] {
jTO7TgCm481XJTT8YBd_QRTWqeXt6Uj5_wjf7wec9HSrAYk35esXB8mymeLmtKEGwnuHmqrurNE0M6kFHsv2Ynu3-FQWJR6i2zb6B3vRv57BqdZtiZGANkfZ
o2eQaBL5Xvy_dopsk0h3-EVEezGsugmVL_ddXaxzkBKgJBZY0w8FWh8m2LzyLTlYpvj2jaSqNVeUa7gSe6Qwx4K0n69jnAFjySfPSdkHMBIsntEgCfOr0HAh
xt7i3fHL0HsxqvNAke1jn5Xxa56tg30zGi2_0VnFu6t7rz_dtaTyRj-w6p-7lBr0gv_mwCrhhMtRUcjjU_kko_KXs3rdWxQ3Q5KPuKyeRenmXgorZsCk_FcZ
9FTQGzkEkoCVdZeZN4BPUe_eoaIFgp0aeKkFsDjfdtebk4Rg0WL3ROk_xIvuZuD5n85_9CvmZQiU6WQN0dygcQ1633lnCwoAttJN0ppzR7_rgcfMgvcfYZ1B
8xX4BgV-aYzxxCRq9pmYOcQfjRgRCk77VE2Zj8yzTaLu6YA9kfiGeZZ2XAyHZl3_aDKxmvSeAA53Zy5mdtmRWmsuvsaFHxWDJU5IwjzSYL18yCvmhIQ6NsDG
WgSdKwJ4y3qwJlBOnYtVSZnNUCRZFT_c-Jt1EomSlKTBhlqKRxcrnsTyl-SvHewdgT5Zx0I9ZAT6NqOm91ATupqCSdixnNDqI8IJVDc38948NAA-9VWQEhSw
b1eznGQPAk7NSgClFRSwh7CyX-SsTuul8xcvEiTprDpmv_Yo1UPMVuwdSCZaStnfkTKd-y9l6-HuY0wPZAVuehchYssEBoEvk_B1ymiy9dUtqXHVD2Ht-EVu
qbyz_BnrAFbYumplFCUNK5MyqL7gpEXFlx3JpLj506Ruqo-WbU1VeLK4W2d-z4j1Cu9daPsFHYAwy5d_2DML4CvEKbq97k79J_XdGEfLcGZnBwRr0pzy7XDy
sIky-NyZ5bKp5RvEHgVumc5m-fSkUXYKcJXSBzctJdqg7d7RlFuR
}

