sprite $Multiplexer [61x29/16z] {
dP5dkeD030DvbcGwzp_kCxjEXozPviUa3arTWUlIphhLTX7QqPhjNplerzBoIkiHNpslHtpvl7lCHNQXLOdNmQyIiTXEVu_Hp4jCe8hCTsGgI9t4x0dGG-u0
5A8hr8VWkyXlPqvugBEOf5L9C314yYuLsN5C8hegqWXY5qsXF09EOvSivP7eNGZr9p54M1KVKegG5Pt4e9dnI313wZn6mjV5VzzPRpkda3g8XssF2NpLPzml
_Ie6XXICXvA5aeXhsqKioOeWqVGXX3nY9SQ-jjtdpdwuyrjSseWVszI97rCf13vKGSJzubs9qGO13d7UdMqQl9L-zQwWSUaRsS-RS5iRsRnB_W4
}

