sprite $Multiplexer [96x46/16z] {
pTI7ZiCm30FGdaH96MZp_tzxiStKtTC6IWoY9V9kLhjZ_lPB-nnE-4CqpxoSyFhNEZ8jNNcdtukdtukdtukdtukdtukdtusdtusdlr-6Q1ruzPSHhMFZgJze
w-3N_D_tWRm8srnBh3pWE6inBOqNVKnHk1cfC8oQmxRHS_k8qdEPBLxqrRZWPkF1_0E_Vu6j4P5KMDlDN4NKrXPvFB_YcwfcWEsgG7rvOrREh_aEm4ME7O0b
0428t9qDYDVyDGcAjHCmk4S2-FQDsJc_vfiZF-W6jmG0WueWOAjRPp_EKMOCB_bYafvZfzeQwtWrGxTPyPgVVvzIsooxQiLzDF_8VOEU1ZWxCC3MtElyeXzH
7d2aGl27yj8srFjJ0CxZYpu6FkXyi3J2s6KsjWVVzcV-_j3rzxzVTBi_k7rWhDwVHtCDw9FVFRa_BlB2N0Fw6x_xzlxarpKXzCdlFha_THwoxpNqoMy-3qmu
ukB-3BVkZo5GPt7KUF79qnVFlyZKbifqQzwVynbrHcxe5e0-UVhriEJMg_lpS1QtBIxP9q-_TJ2Ix-JR8VFqrunjKtW6FYtUClpTr_WojGpv6YnDSpZd_m4
}

