sprite $PDA [96x129/16z] {
xDhN0LmX30NHbGWF7FklredDSNmjEKy11z2ls1qQ7nDwNm_y_9ZIUyRhCLxlZ1yzjh7y8rzYgs-NdyNFvIVnPIu_Zrz-J-EN_-ORNsChyy9_ruEhb_xRtzd_
xsyex3-MnrNp8k2toxxpk9T-gySpwfSQFcwX3VZrSUrvnO7VTZYxBjOtmU-rO_vtz1lsBTStsTTvAs3-wRxEUvHlkRuzz7koto9yo_NDKkTZlyntDX-T3xY_
9VYGPtuJVSU-naVubk13FjTtqUSyzpV6wxx0f_ek-1gl-vReSzuhyLLUzobVDD_oVCvptpYVwxle2xpiMxJVDuDyhk-wB_2QRpa-uNL_0Dy3VCRhlgNvWC_q
FS1dlEvRfY_psDTuwZDUzqszVcd45tdiQto0xp6-QzVdlinNu6_31LxnEVy7-837li9pVxh0_yO-vxdFUSdd_1_W0rxmCQ_xdDTz_tL-KVt2FDLlTXQxzZ6o
NwRWPMs5zkDhjyp0G-9-lptiN_l_C4AxzMjel-VynxUs7_JdF1F6vrhDG-cL48J2fWfoIDx_RQzYY3BNcFoDL8R3Dy3EzcKQ_wLcb8ADyZsVG8JY7WeLTGZH
iMrYuFJ_bFY0hstT5EgEvBhgPWp--JhuQ4guyjgKyfPFt5Pz5-9KdQjEzLSNiv9MoZs_hlhFh9Oq-64-J2-K-_cWwhAmTrqTmfAVJUdpGLCotlCPn7ZgbBVB
b-5vEIYtryTAeI5ZRoNozyhFroyIe4pyDcN4w7RzmfvFzsRoWfyjYXtVqYNmYuXa_sy4NS-7S3Vp-LXUv9lYVAjVOpqCEHk-LJ_g5tDou8l5KtZmjYVHidu5
L1KZDXLsCuzdVbUSKWYer-7ptoyRZBvZ_PS7dbF2hCi2WCRQ02pmgvZdEGU6HqefUmE_QDJdfNOnhq-1VirOElsEXhS6_iGuFQpy1Lsd9-duz-dnFlX9VXCE
EatiVm
}

