sprite $PDA [62x83/16z] {
pTZPagmW383XHaX2aENzt_P4q7PccbH5FTi_cqNuXDlfrrOexLPfmrxmlGI7sbfPBvU5ZMkl42w7HRIlWeE_7B3eSV8Tp9jiBT-uDd3NkLN2wz5_hkaZJGF0
rCLtBCMvXezcBqE4gGvXcUL_j0H5lzJSsNNj_hG6LRidslqxxPvezqIx9zhzNhsese9rRS5sxQOQRch1kWO3DcWDcxIEdsjlq0esQ0NRjNkWTQnhLBLWWzQn
HUlupsiDsxHJi4cZq_6VrmesQWKRjGK_qLxN9XoiUhcbTVn4UuFMiKNhsAwNHrh1gYOoOD6eQntRzN9Bw_Y9zXQzQ8SQD7edgKSUWQ9bvAT0WdUew7VmhV_x
Vq6OXbimRN8suOZs1vRIVFIX8rEYZc9at8e1i6jYudYCQAev1DmK2OgnQm_GDOECnXuWdcj0Ibq3ygxzeO7s1uoAvhWUrrlfcuuSqpcQQYJU1qbs31s6HaeS
nzBuCtIgRtssrfffQDXrhBKoxfswjL9Q6NjpwOZaFYr-EvkhBAtRR2qvlhMiehnW72axqZVDdD9cCCjAVpDl3uVEykpgSNQffQEqt_oCoxv2kHR6NfH3gdyb
kTGOqJ0aVSFdwDp3LJ3k7t3bQvNQ1CDBmjfkL7bvzI1VjZdwONy1
}

