sprite $Personal_computer [96x96/16z] {
xTY9OgCW4CPn5MO6C0dl_xPhOfglKUAW8tl_TtktFqUWPrTek6LR1Al8NyLK5eLtlIMVfIdFMPhoy9lmy9lmy9lmy9lmy9lmy9lmcxxaQ8kt_P2TgLFy_pvj
vzVjytdTzYMSqIU5D_gQViJlrmsBu1xmkrMb2vteGqUs-VNXZRu-lDtNX_ScN-Vt-_JcAxh5ruS_wbFDnlevD-prfsg6D_awR_BxMjrJmPVCcb_94vNyb7l5
LpOMVD6_NZh5hroRiYzPDBzs-AMFvT5zVVYbZ-LHVNrZF_gIHVK7RVXNlFAnF6NV4_cXSdZcjJ_UEiNtNjjOyEpwfNzL_2bbRQ0RV7LjJBw-iIPV7zxgAyFR
VATihDLNXZVxol1sNsruTS0lOn3Vsk-x8zNxhgtlZFxrN1z78l6zIxvTlZM-UCxvAC_CBp_TqVJL9ODFwQXFH0yV-VcG3Ic37w8p11zN63Zb5z_tIPv5FDtH
oEzvnvCFld_DptYwUtv4VFV1d-nxVlZW-nXYJDyRKsttZmiBVlR1Fng8lvAt61N-5a6Cm3zyyBX22GEAdBlRInpyv8DVN04LO9ehoE1dFr_3kZWtnXIFb9ZX
H_Sf4X9-IxWcYNL-87Qe_i3omlSa8QKeJEwjw7w5Jrm8vrTs-9v9fkOFbwc7JsvnY1xFOeHwduX39F5CuYK62hFlywfmmFUHvndHx2z_hC0hF_XFnlitduBm
8dbIFf93clyX5dQB65GxNtYhKEypOp1bViGxVMxd2-m_nzVFfzt7vrVB-LqaQkjxjlhZfk-AlcmMllifXxtpwy5FENORlj1H7_oMJy4B7oc2x_9rFBqB-2ud
Fhq4liiZpmKZ2a8I-CbtSoVuCai-WPzyUMRtmmo51BxBbtHwL_3TBJSeTAz-
}

