sprite $Personal_computer [62x62/16z] {
jTE74k8w38LX7Eb8jYdl_xXNqP1W4Krmxkx-zFBDeTw6Idi-vdgHWu1hfxdumGVT-bAcMd3GfRPfB45VN9PlNLgRnq5VNJveUkfiSjHyfxdmZpJ6-DYfPXd2
Ni3d6h6m_5DlzvLtopk7FpNTzeA_giCspUfyU5xdmyo_D5pdsFgbGMwzQETqFZohu_28mSj7wwDyQtAT3mD1jsucrJcE-e5KfvPnq4kgCmnF1btxBTN11Zpg
NXFDJFcmuLbDHomof_FXMPqENzCSyRpEOlAMYte9_THqtfcUYDcrFhk81yTBdz4CCAhf-xstjVvQSUbDPxHbsWClfSZJb-jIPKt5pqxIjruzr7GnN7oRGHRe
97mqnBJXKeg8rbgR7STgI7Kz-s3JlkmjB25iyJkiOi2cxvq_YUv9JB-2k7uAOZ9GFV_iJ8CX8ipqJW3Q0kLXqDfwbLqhm5iWnfZ0urDTjxSgfgLPVQqrPR8u
QAbDiMbMOS6Q263QFB1zvedsTcreJqmJk_4IJI7Jdp-wKS4XmQd6e46XcMtw0uqzkQmLJFzxcxur7yAcQwOHzB5DwqCFMWJ3IfvfnxTNrLXj4tLnl6aPKZbB
rvfZqm9BPJvOpR7ffjUgwwaRTlrw_ezUXjV-0m
}

