sprite $Plotter [61x46/16z] {
dTC7akGW38LXFIKawFkVTssSs3Ic-IkDgjutdSap5ijqnseMpNGnBr7TLPRQiRcjOrLTnz9Rmwsi5ytkzAuVusNZSUOZTXwIyU_Xn8FB-9gTwQolYCQJpg3F
ViIkSgRCCiRy4FiFbhk_iFo0US-5tcCzrZTMjosVn6vxlk7KJsQQzF-WCf7wFhEesOm0MCUbR5hrrPQEKq4zTLMrD81U0nVTidfjKTsY2j4C9hLqZwIhebgI
_i9WPlo5jxdfAsPpT-Cbp7w41GmziKvY7bVdBwSuliPWSnTuPXPyYR5Z8qB9h8ufZA7ZzssPBHbFSnYo3oLRg_8zXef8QHlc1IpkdXkE5GprKlkpNi5iMMie
5d3dmi04XhWoNdemnFd6BSEZyhljU9iNpxYmYNXrcgXZ4orLBwoIJMaQgzOg_OeDMmfD5gRkoTJZDEl7NDBdEAzGyBn5CkIsKe2YD9iPE9ZEYa23fWk1EPqX
627J5W44Xek3ffCoF33XysaoZtMRupajbRx8X_al
}

