sprite $Plotter [96x72/16z] {
xTP7OiCs48NXwUZG_M-R8LH1DqK4iyhd_XQ_nzq0rkffMW2hXAU9yTIyfDZrF6RU5nNXSuJHDmkdzeEPdDbNYNfYdt_rVp-T9_uNz-iVRFFkF1ltsoGOxn6H
y9vycOKescpqUHOP9eHkR7_CY61lVFz4mId4v4RehvdUxDEvVTCPENLlpE6DVY0MVg6FP_p7BFpU_GAVuT_wX5SKXE0p1FRixFh1he8UwgizZ6fiTEi_FgB8
Z5_H6uH2b4U7NMe4bxQ9zrtbD_o7Hp-cvZe183bztkzKrQx-zRyBZ_jpy2pSoRrliQeIV0HDowDV55v8lE-D0Jxj8ppkZmtX1PKMGaYn5eOZVSivrwsKCiow
CCTG0GxrHubPGloeZqHuNX_LDeBdzDbk5C_eapqehk-ZlP3rVR9NkBmlEfYgcIgjxgFOHZaDXclxUEqh08v-JBYoZxS-E4wR4d5jdppFi0b-VYc5F-ypVaFC
O10_t_i1zuxrIMzz6kUNjBYFn33Wo9UykE-KYKYi3Ec4lcr26SBwFjacbu5nZuxsKPxd6vxGHva-E-lxABcuf7XEtx4A8vxM7uxqqVAYFiNufM-jvLYoq2VW
fLzIhodtEFNjKeHTlZ1yRFH3I-oazwdFvAFrod2iVokbdd3N9wuz0wpeMsyHODVNNW8jwVln0VVzs4RyS5-v5dX1e-zvE2fMxmUkQLfRC3DPaETcJcgSrfGG
aVHu7ffifJ9VZvryvKvmb1LqeS8aHNHLuR3ReRXRqOK2XqcP3ftMZd1OKGzftQ_cQqnmN4VN26QD5frFrKDIltklMk0upLug0ZEyTCTmNEYkmPwcb0HMi9Go
mHSnHrW2Kmum-mS
}

