sprite $Printer [96x72/16z] {
xTBTTgmW38PX8IG4j7B_TxkLRuq3ktMgh7ZMj_yjVOGm4ugNojDeqM2LgV_dEmh1F-S7gVc7V1P1PEB_FmcI8zUj6ipnr2NlGhDAZ0RaU4-OHPWVk02Fk-Mq
fMpWzmDoNZ1utlrPtiyr6P1pxlN2qTsVzs-H3lkUMvy4EmqffNb-FvlOu01kYm7vVVjpdWmEu6BhUyAtEkyrnno_OgR3tsFo5AJokLyrMdITBrkn-jsUqp9V
BqzjwXhVxtwUztmtntozfNJ_kIpj0qW4q-TspLRoxcAfTFmQrBSFg7mE7R-dT8rd-0TFpaK-eErJ40wkuv5cxPAVUKcbvxTmX9zpHo4n7ONaV-RXltaKe_l8
evZuDnv-ooCV4xlFFbR5K7awuU5tF59XLPLVqsN9Sivd-DzumUsbQ_bJNk63jmnyZF0Vup6VXtYDC-utbQIMPNdj7ljVPp8jYKYgFEPVb4BVc0i5lbI--g4m
iRGD-bK9n0h-TRzf9ICVszUu--1t_skcqF4yoel8QppWgr_KojyY-BZVwfkEduaO-zzu-6abqpI-UFXVvg_-wilBBqioBGiwVBNV_xZ_vmlVAiezNxox4scy
uG_mSiCVuc_u8xpUy4Tu-Un_hV27UP5F_bm8_Z0VwPE_B1DyA_xSLxbLwlWJFnKzVA5RAVXJ7toUXdtm7tpmm_C1V-w37zy_-7CV_BWF_iG7t_dnPdJcTpny
m-0h-6TyyC_vu0y_Hp7rCVkZjPHLBGFVfAiOfk0x_paU_dCy_6HL1jydnQxl_3y
}

