sprite $Printer [61x46/16z] {
hT07bjim38HX4MK0gkJ-nmsewaeBUVcth_sz8JL4el8nqF0x6Jv7vGRcR__Fui9C_ue9aPO49Zft5IqvJZ5adXYfwiEqfB34AdcjLlBdBWmDKdr4_jo5bEEx
rMdSDkNEz3PHIcbdA1YdYROZtRerqwvPHUiqrNsIePqE3Tgd5HR3s751zM_LvLYEj-yQOUsmfIYNB-boM2sotNie8dJQIDomPdYoOijfstNfvJ5kCLI4MS1F
5e5F6wa9qn5VQOphcstuicImBtdrL-k1BvieR6sOPkDiRTSRzX7P70XR0qygPpSsMojknwPP57jtiAge0M43woZ8OAWW2WjRtCzblO5ZM68OOGFFu6GRHiEB
MpP7j67DB_zlBDqW7In2fPDO1_-m3DCExbkpByktTWtlUF8DS_--aV8xbXL3UmM5yXlsYLQit4cyxRvXdsMuiUpdxeN3yh1XbLxNxeNRxe7xyHjkknjE5dZR
3Gn9usqtckVHajNOtSE8N7xP0PEbkcoaVvPS3_Ol
}

