sprite $Repeater [96x33/16z] {
lT87aeOW38PXJVc0l-N-jzqe6hPNikyuZVBOMA9g2Js2RrOmlOiD7klqk5agZsQflFkflFkfVFTh6kz-Akz-Akz-4X--NSlq6fxvbQS4GFUhCDS4NmYwCbHg
ZWyj4A3KIv8FTLuKoF57_-xJtDxwZ4WzybwCW6cF8KG2_hPV7hVDfz9XsM8SVWpvI0-ap4huqW_-ldO_A4-x_sn8mtSQt_63NtOVGoTbyhZ4Y0_HaGgHA7tj
1zzzrLEd4yCOOVdn_ms--uJJeZNyPoC_zpiVVed3euUcY27yt0z-oJd_mM_-z6hmENuBtdspHvlRnGQ_Y3R3tFhJHsfjQWSVYStj9Vy4
}

