sprite $Repeater [61x21/16z] {
dT05OiCm38LXLtgIQSxzZxi8ncZ_9TFNDYdMepsTT3bkWsa_MMuxFVRZkiwj6ZwrXa-juJOEhU5LTQFgQTN4mlyFK8Wez0YhYcexnD49VkiT5fM8Y3N7e3l0
dbzBFEOIilC064I8CVC_S9zqOpzk4P70nkHZoi5N7FPHRim2bubZ-5libefXGcI24VsEmnhc_TAMQpJThOwm1MtMtUnUHRZMRfFIFWC
}

