sprite $Ring_network [96x30/16z] {
rTQ5bG8140JHQPlBF-DxkBEA_G0ArhkU0YWv3rWYK3E0sWOiFYa0fEma4J4shKrOnCJ_uoH2FSKaOir69M7T1SUi5T0nwehQgDN0hJgJi5R6fFOSr0iWherc
lGXxaqUz3BgCUY4uzLBvyNx_T1zwQHzwPH_I2_lGLXklY9FKXdFsVW3MQlFG_pj_ls5dGHeyaUI-U3_ZtEpogT--_BxWliVH3JxWplNtSImEKbftNgNX6drt
6y_soVo-qXsEsrVJ-l8cBKpOXwU1-B0lsKdtX7tuUDzs-cZRt1zcFVKF
}

