sprite $Ring_network [61x19/16z] {
nSl5eSDG00D1QVUb_v8_X9bjptrogdy0pm7zavkgqBMSwnfeSwuWpJEAqEmXRPxN8bc3vdM593RlgOVxpZRlMont-FvbvTjLL_QDMC0_sUps-RYX8mdGT2_f
jRF6WOEi8RsF4xgfMmNbJZjm36dELMNjMdQBtDG_e8uJ2hJDgLy
}

