sprite $Room [96x63/16z] {
xSutcWKX3C1W1eVP-rzuN-v4XKf4SFT_7bXO_J4_dAwk9JzZluvSyL7NVXMvuZCjd_dGVEOrdtdDPzxpaLTzviFtyykhFcol-i2hFl2g3xpg0w_wmAi-yAeF
lEe3h_h0gtw_hH_l-_6Pbd_yun__-CVltAvoxVVORbQ0R_BWcppuDZ_0DtdmJHvyamVVvCdlI-F1DtdmJHvyamVVvC4tUV0zlWRuvlRWcppu9a--o9D_vtxz
uS5tAk1L7tZL1rxraHyLKlV07W
}

