sprite $Router [62x22/16z] {
dS-70fim38JXMASxEPZq_H-tbasR1Ht-4xO-ncqK-r8_9jwm4XyJMra8aLeRbZ1JnoAMkjOYPkfeIzYer7kD8ybXr-Fmd3-gqj1DoKdlKIHnHabgZemqjReM
lAREuAvMHGNWSdY8kZSvuFwf6LtVQtrgGBiRMWLgw_eXe0LmegdK73rrGzTkfKOfsFE0PvfQrubL7tT_DhGJPW4hP2bMpOmuz3CEl7l5aVKmF2mhcMNJpe6Z
0zzUtpmTVcVl1y3xToT-wj54ttr_T-9l_VtcQRzqujIXRFg_wWv7zuwphSKp-RLcHDIO9HxvlZrhRGlwcuQJYgtrIyyIZuhYBP4QiVThypc3sz5F
}

