sprite $Router [96x34/16z] {
jTG7UiCW38RXMA3bnVrlMsJwnyrZqytNtOfNTENnpCk0zW-yoR_dvUHb-lVewTiG7lSVnSCVnCCVnCCVnCCVnCEteYDu-4FuITwRopxxCtEhQVuHHMmrDpzR
mAkNNLeSvOZLJUbxE5TOyX4Z4GSl5lwigZR3Zr8sC_bYHrQ3VU-hP0_V9ahvrO_ObirCcJCJrLqfJHDHuioYyIKvnhf-yDByolFLJrQMH2dkeBMrhAfgMt7E
f6M9ePuFlldBNFCxFr5jtb9SVv_hAqf5gQObHJqVVFE5exw_qE7RTFZy3H_yA1_yA1-yxjig4J_xuBDtVNRu5xncmKVRJavdRJwMu7JxxE4JXKy9e-3ZIfY5
mq_-iM0I0w4ah20qjGW1pudmwHEIat_S_FnJS2aVEph-QTFDZyXF_kf7uOOMHy-r6T0n4JRmYm--wqUuzddnrq-agEE3x_ZeLSKYs5qV_DS-ElNl-0f-a1yy
_6Nsbfcg2l_APr4pHy4ZtbPfLTtC_7Wi_RQVnOyJPYgeyMZUx58zeVahdxN92867N-xRryKuNVsuyhoisruwWKVKBR4QKdjFESVMVg_w6m
}

