sprite $Satellite_dish [96x97/16z] {
tPc7jkCg34KHI81ev___zeLbv-AuaRovK_SgCxVjitHaasRsKAn0pS6Pdu9jgANK1jH0Fy5VeIbd3I5L8DdlraUeVn0qvwG5oD-SWE8xyi37bFiCtzcI8Ap-
bRxi_7shLhZ5FmWLBSNmFHcbsAT_41lKSeYHVxYgccdu1ncDZJ7En-X_QE4jamp_wmZh_I7n1yggcSO2TYFKBolrieJCvvHATExds13DuF-LbHeHd_jP2ZAP
mMbPzdwg04Vsmi-iQ4DsLXQn1BdpCpoHNFavD7Wps9T5JdpGkm224jdXtmT8HJ8NM2yFVKmwMV3r09sCSbbnrslMsGB8tlWvZYNiuQYQykq2B28HyOsVVGER
KoIcd8EvfLPwSBc0TGdnl1vZEPfx0eI8tFK0dG8zrJ-O-Gc97iZr09sCVAutmKn8w1ksztvML3hJ6-Q9tqAxtrqLD2uZkzU_Dq26VVYjo7r06053Frj0Xn6x
tqxyxD7Sq4_zWmpN_MuQqE0EUYDsvdTGs-69dwM1kr5UZo4p8y7PZhmH84F_Ta4MsRuPKA5YFlMR26yxRk9V9tZ5avbIctrl1J5My6vzClSBzAAXlPxb413D
d0oU1dJzKf7xs4-jscb0rvy4X8bxD7Izuw4_1Z2RDyYGYu2X7tToivyEGAsvYuk8EnfVpoBQBM0A8r-jOEX7GFtKRoB22F2T4R3g1m5bTyJDAH2xiFZ3Lq3N
xr2eMI5lp6ShiDBr3_og5pwG43uio33AedTkqSVe5xsS11J8XtuJeAlVTNzy44HLv3IWWdT7t0mk2AlVTNqdwVLXskpkY9kWfi2lVkv-rPo3N0LurC-kKEex
viNlfFjBZj5V1WIa3_pSnxIephfdW2QDsm0vluZ2c-rq6DMj-AYwxFWoeC2zUyH5UXwbPGJ4JWYoORzZ6WDCsbdno2y1wtqsE1uKyRrsLkAOGBfz-4yI577r
pzePjEQUIDVti-uoeO2Dk5axEMoenMu3_F1lsQnWUiIHqe1RiIE0_V2VHWIaUK72crMKxX_8u3GYGzvOm6OLtJyF6BGMQEQdE2xKdNyQ4935lDkGchr_7f2G
p9iDHHf-TYliUD8GvdwAIplTJukVd_vPG8IQAS8zO_M_1F23-uugh9cYfBJpBmay3V38SpzbDWS_2ZkU1rIuZ_qzG80gtBbVGaQPzsEKZlw45fXd8sYU3k3T
ThzhW23OYZGDy6cs0HlMkwpxnm08XjBeYFcge0mxQQUZDFmTHe_rQ74Ia0FYdJuiwHI__7RuZQt8SjkHXjfcxNI4Z_vEt8xWlUm9gd2pTZfAtKzxlt4LPHr1
MFo3Gq5Xraw7ujDlXtyT0RfkWDcl3B-qVALttWouNlYDRKj9NSVYNqc-r2j_qR01Jx_j_Xm6MXjAwFvZGemP5_f8-f9MQ0Iyb1fT2409Qy1hGYhjyhcR3UT-
--9tOeHD06gKumovbLCzwN8uxFnqzElwB3usjEJt2HN-vhcRpltUVVsYhq3HbuY2TFV0RiFUJpi_nUqlEcr0pHgM3m8o4E-Vc7Xtxn_FuEMvZbZmHNBJ6tVl
fnU_zLz1Thlo46FqR0QnRG2E_qMXbUv7MzZ-8jgHkEeLEGrg6fIS5ZoD04qFSYwrba4h1v2V-aI3P6c3qYKsRIzrLR-dvHEzC7s2TS-GTE4V-iyPEs6MKt_N
ss_2zHIHLp-g_WJoy2Vt4z1_m5yXFzDVuSrFz7Vzp_EdfzwWff_0-1mQFmTlLlu3
}

