sprite $Satellite [96x66/16z] {
xTLdUkGW381XrC6WoVrlkqp5IVoaIjk__xnJRA7ocQ2xToXf3GKGJ-Ef0o1kakLhcppMckNBz8aoVPn-o_I9EDVdB1-q-wPgDavT8Let7qrenioYcxj5wkoD
4EdgpqHqSmxZTKpzcJzJroZV4L_xeWunF6qmyTT-vnYVDvXkfay8bEe3SAfFX9d-n5DzEEjtLtGMxJFJy_crI9yEvjSY_SF_VuJvy4VuCexphkTC3jvF7c_N
b-wZsd4NlXfTVLa-hpD7LNTQkkaRLLll9m3gnJ-zUSQ6yuVrtVylUFFRExfyJA_UyTB4PPVM67tKotxXsNs_pvR_fbxyoSSR-Q3BVk6N-zrKjt6SEvSLlDbk
Vccw-_rkNU2mBztFH0IGEBzJJ_RFTjv-8KhUNxZpbKKpVG4WpVG90ADz4hrcAY8SwvDCzf6PgGRwA0kNQsQ1lYryPM7-UA7pjH7bzuUkPihtUf2FuwPB5KIf
awPp7KfClLrvDKAaskg5rwr4DThUDviwwe0ILXicmlBmKNehaM4RpVJcjpesAj5nU_9gLllJu98GUBtUR-QKuG-T-cMwr8FfDGNCecO3utqwAU4bqXEL-6Zp
MnkLh13Bwg_p__kGx9D89ezYbkc3LYgVwWS
}

