sprite $Satellite_dish [62x63/16z] {
fTM7ckeW441XfWymUD__RIy1bOt1hMTx-Jy6r2IjB6wj6gLVPQtMKg8L_WMcPghgESUjoe-rbuv5HDNApzUlTkYPTYzC-7qTClNCeZ8Y2m5yKv-ubARzjq3S
Wozr5PfwBL_cw00aWfyFKHJbf5bAhCD3OcOQtp5TjMNWisRnCVqAHHZP_Cev0EMaUzPoEWUYNkIYCGX8NZHBhPXEIIu5qwNiQ_7t78MDqpNQBTxBZJzWxX-O
DeK2yePxo4USW7PQAo9kD5lJXNkoqrW5aNPSmnPUUhCuRpHhiuNVR1n2EvSj3nzunccN19qvBzuAhFzBsuftJJkk7hxMXgscnftpLOknXgPxX6cRLTfnjNbq
wzYsGNMyRbrDU71PnxQDcboshYxC9oxfJLffSbMP3Jope7ListB1mLLD5xxdWMazrJVXt3ghzVJ0mgjS1-VFxYfT4vkvktLyuhL-haL3kYRfEXULCvVgnmhm
1XCb3UwQfEFiaylYJTzhE8RoojHJp-ucBzmQxOvjFHYG7xnhbHUVAoHvD_SHb4A3cptqybBpNeFpp2iEBbshl3vpGmXtN66MxvfuuUKjc7SQv-Ja1HzSDfNA
xqyDMQP-owDiDHpd8R3qdliDjnpfM7zgddh7QqxRX3Wzz17nZclZhOOC3qqijyoZx-wScGuDY4D7aItFZTxlUsgIe1AwunPveu_joD81oSBboZK7xHzleg5n
wiIrNgTN3ttpN6ChC3T-w0GUMIRN9_TSTi-L7kIFkiSHrZ6pw2FtzgB5rsjuZCvDUUGrgib8PrPUD19Z6aaP6kVQFI6nTlZ5QxjSbMHfmAK94oDOH7uEOCqk
vurqqdJNCl-CKbiKLpdcThXUbHYV6fvQxgFrG7ADrcgUosYv5-MenlmU1gTRVVwkH2sZGqVr0rleBElCnZSCay_JpRDIyhCI7MimZ8ZW7i9Byx4RpozzvbrR
C7w_UQ5O-fRjDsMRMkWtwH-rXVz1HuQkJNwJDq-zVxVVbU7G_m4
}

