sprite $Satellite [61x42/16z] {
lTHN4fqm44HHQRfx0dZ_wtM9vqHmaAZo_J-WtFwGPQMrnPnTiOe3nbp7q3hcAeQoNB6bC4jxX0Y0zAZiSpPXXWDJyfhISFi5gp23wOPVSF9_Odk5mOzSmFWv
RFTwC-o_uNvAFkm9zuS-bBMT2_VG3vnYRhU-rFWfAyDlOKGOfTmh_5pafZx-MZTQGJE0rF7d2B-KDQZsBMzL-a67rl6RIwKsqaDiT9Y1Fov6w5p_w_7iTjcg
XREzWh_lizvS3C5K2vWQ4PZ5aFzi4eSVwMWMrqUwECefZ1hMdN8I2BIPCYGvZUc0OlRHJpzmEDrxcymyzb3ivMZpzNAINjOMOagKfzQmZv9j9GC4M5jjLRx7
_Oqbrx75d_5N
}

