sprite $Scanner [62x37/16z] {
fT57biCm30HH4O4cG8VxttRWj2BHq3otWrPVfJ0VjuddSgHhVHeJchhnaQ_F8TJ0r5rXVvHzgVhOu_jtxElxD-nxrJTXm5dT6VYgpqLVfocZQVYY3ts7rt_K
_VbJNuf-U1Mq2-nJSBnnpVLb92_jFMfDhX2txrOkrBZV88vZqCqvdbYwUOuvy8x6tcMpbc0Zfepo1tlBovJP5vQYdD1_bHTwgfnapvKpol9vLRYyfO4_PGBb
VJReYNAQbQfi0HAwb15UgUYhRAYSPGENhsfb7nd3sAX9eEmC47SNnfCS7zwrs4XVLMYLOZFAsUnQRMxAVm
}

