sprite $Scanner [96x57/16z] {
xTLLeiCm44FH6cQ2jlU_sZAZfCTmluf7AQOseNu1b-PMB75vPHRYrEOKk3OBWLh8_C90BaGkBn-zO3zquUFVfVy5--aBe_2_LDhu4nV-5_n_uVKlhhXnzTHv
UgnkR4E3-Q7cm1QxHl4vxSjFictTXZVO7sfQyyUhuQPucSKDxrrZU1G_yZvLWWVnTNxa8yu7K4z9uq5Sv14y9fKtyD3NcS93kCv3xul-va27hlCGhlF0-wBn
upd_7DTv54zPukC6HtILnt2Hnt2PXtITXt2TXt2TXtITXt2Tn_1pVcPuHDVvBX-pU_bPWUFBcWyHZ-LpfCFvq8QERe3vjM-9heTutHzWVksxqPKQ5cXDw0M_
0W
}

