sprite $Server [96x212/16z] {
xTi7akem383Xn5QnJBl_RLz4CizX1nDZHLlpRvd6V3GXRnsUXxTzIizvkksL9w_L-7COpKNr7Nc5F7cLF7cbF7crF7d5F7dLF7dbF7drF7a5FNaLFNabFNar
FNb5FNbLFNbbFNbrFNc5FNcLFNcbFNcrjOkzJ7MVxANB2p_Qep_l7pxqrExphITezy_nZSBSJ_N3p_P3lt-InZfzYMqPVC2jmEHdtafCleJIM0h_YqO_RWGs
dzDMQFAH6UE701Q9POfCFftFASQ8zw96EVCftIs1gMpobu8-fSjh3eI9BefbH2Gn-zg4puyAf9mvPxnBR7xyIn2NW53raiclT_WPskhrMTf2Z_Chh7Bmmy_s
mnx-ARSb_lD_-CYoYX7sy5CH4y6pQyicNw0sZt59ZFuflIgZhtyo-rfy7cZPv9DinLxp3xDF9X-krtFLrqyWDXyHQduMBVtX_SEoKPhRyNmFbNRomu_oYJSZ
3JhzJ6tjDPz0d2GnmMxpZwaaaWWX0h9EPWaCFXFS-_ZSblqCOlAnFZXnpkIJh6DK0Z39gcpn7m9AAYV61P9xYpzs-lK4D3-Vru_FsE4dQOiw_NNXTUEtzhVv
R-bBOpngZkVxB_GF__0pjzNh0xu8Ig73RzuyshVrjtcBZrG97ukTVgQsVk7hw_0FFtZxILwNbgZB3-shnyCVZNxuMd_SmPVjUfzVvVtcqzyFFzi_VGF_y3Et
rUi3FWIrGeTVRwnq-8N_kVxui_rn7_zwVhytVE2EABRuzWx_y3cbf2D7j9mhJnnOfnTxmq-oleAQhoeHCUlD4Vv6FZnMJ4I0rMLmYgRsUVt2tKBmcXyack-2
Zmz4OHn31BkFH3W7SxCFOmYnwXlcf_ZALvvVkuyXA6-VJxg7scf04K5veryF49GFSQvpFzHJyTZFMle_FbHRRn5AYBljPt3Tpq24iFz-BdmCyUD-HfgoxsSD
OMFz67t0eBgZNtYJJne-xXzjWz_xV8VoxAP4xby_s1yVk_z6yA4__Fzt5SfrFYCiuTANpcVQE5-CFa_sHVtsGCEf6M1yvUVRxHeSv-TykwN1pLV-Xdw-yZmC
zQyF3NxXXzxzpFNzNFWfb_al_53x_iBa5tvmsCzhtc5-2k_Z5rwhxkTUVyrtpQU6SuJ5Vy8xpEVCF_NvWU_n2r_gtCz86cFnF_0EyrDu1x_mFdxXVVmAhpup
sFsdlFhQXOt9hS8FrzlKrQRdyxN63p6V9fzCuRd6QwFPBtp5jwQymJVmcdZo_m
}

