sprite $Server [48x106/16z] {
rTRhbkem28PXMpuWgTlT-x_RgRAa1peaSvvvVpzc4PRQNjPaRdTRkSxNqkhVlE7Jq8gc-KrStFTnzttSVHzttyVTzt7tVTnz7tVVoTtFjzhgAbjVgLNzRe-f
lfQUUIvqrhXKFykhn91uGOWayye7hhcts99xkUVA1808AaoaghctZH1HMGAfjBm7a9NxKEgBUZtxFpHQd-YBnlYDzqrzYDkUFLdAlQeSoZtBjbehvruhhK7J
yxL_F-xN-1abtXit9LubXiGB1vxFhzXCGqGGSF_vMcl56_OfecNnGtkVl4Q9jyPzGtA-nnvbdcByXxnAZ19FD8Pb3ed7Fhet9buvzeVsEQh4aFYup6oVWJTz
aHWIdzptHxnoBFDqKkS-1w_B3v_l9ptauDI3Nmq_yJvC8imCW3myE_Mbg0hpphEebigd7jO3siUmr7DV28r0QtvL4UQx0uz4Q9slgku9pVctFOT9zfFMlqzc
4SMf5xikxf01yuyBjEVlcOVPBmUyTtxnURBptODv0VYaxxDypVVvPZw6U-7xLcPvo_mwtuR3zzFoxxFjP-NZPVlzJ-StRZuKliyspCKymKhcDxwKV9yNf6pU
-UNq_yTzCM_SVQFglDCNu-Pl4pUw6hUk_sV9cnxSA_EKPzoJEU_0Nm
}

