sprite $Telephone [96x76/16z] {
jPQ1ZhCW40OB2miAiE__jlzfl1M_qWP-lKd27QQPJ3UOylf4pO2aubwFiGHu41RZydF-ydgP1al56bhTW_ccXNxoYLpzgtotvPEJFyntH6kDVWuxdE-9V4eo
IHtEzqGhHobJY8pcMoANcCNCa4I63y-Mprnfnbz5vlAvn0dzglsZ-LpzJ7uKcSjVwap-6aGcytacdy4_dM-fosz-nz_DT-L3lYCYXn3zvlCgCfAVgkldUoBY
cblASkPpbJYIdtBevllTdxXbMIxvPYG_hAcRpxk_N8dJ-RKKwPrzl_kHCp-EvZEdsijdz-tmy2fbQFfxU-fD_zlPPovInl8t966-xPirFw2_dr_IJXPlXj3y
XFFfvtiTR0k70mviz7-ExipF2_Yx-Mktp-gNUR7rf9jmvkS8_du-TVt1ADnih6_o6VnJ-Vh9BLytbtprp-VpYJV1wyQr-UZlvy-Y-U3lvdFi2ZmhPFZ4jldW
x_ziPVjb-g_NVdXqSva--li_Mp7yx-41_ySBSo__rElPnyE3_du-EI63H5AusJZ8L__NIqEEx_sa64CdaA_-R_bfpQQ3XOskcW_-ptUU-kR-mU-hinj4suOy
v1z-pRVK0XTcd8up-xfld3qUOVxcrtoweFbp5qxDHtzT0Stdl8821jwTFlgp0p9Sc3lJyVl6aKwdoKT_miJKtZZHJyVqwPm-jVaZViWVmXxv0_uC-GDWFiwV
Md9_-XlEDAlT80Vv7JzTITv_cBvxdxuZp4T_nVCVe-RZ5sXNVTJB3rNIQoT80hzFDwQl-cgFV944I3poePxQrHuRo4Tz40cLhopoba_wEhdVDunm-gW_ygD9
XQ-aqiktnvzsnVnJh_dMcBhobLhcfuzwpJU6v8tvLnVrcdyBpKUzvjz5yr7_VBxgDR-assY-wXMH66vJD5_rfz_JNLpPya7_h3zaq3_ipn7qp_f31lt3_Xn1
_wo_vaQF_fnIylVy4bMFoCQTTop_K4uzuhRNGrQ-1UYH9ElZUlG_hqV_ythqFwzN_yDwzAVmlqG1VTT_0z3t27A3_5t_3m
}

