sprite $Telephone [62x49/16z] {
bPG9hiCW30KBDbw0allVzZTnmF2xA1cfgpHwcZRXiH9KEbeqFUv1y0WdZ23XbXmuT50YyBrnmYv7Je0vfv_W8aT--3GWwRFzOjl-LViq0WfL-4LTx21BTH8g
6Bw3p-tRTDgdgS1tEMhUlbL782R9lwRpRA_JQP_EQNm32p64eBpONWqYceGunp64o5cDBFiCAZshopnDasQbwJUB2L5q4FTgreQVgxaybKIzCG4awk1HJRM4
ZzMan9MdwWHn8XpLtDJ_wwLQcBNw3sx2J58Ij-Tg8U4N0lqBDFghLTChpgkzKOum1wFDzLUhLdMRSAhcHOvWFOZs4OzgoZpiiFpWQoMWqL-ZLOlRD5Kdd_vS
RTCqxAKw2YpLvqj_ZLOjRlyxKlH3DVoh9hC_t5nb2aSuGB0tezhjkHe19UCyRlJNFZti826U7DEYoTrz3W3EnwXscobrx4WHcQUdn_5aqyDM7cGxKjJT1Rkl
RNfi-vB0sv4IfuTLSwPljXyfdy5C8hCjY72Ywq7gFvTDUxNREK67nQezUtdu3_v2chnaR9axKgnwwCjZL9jSmpxTYWwz2EVv59uVvv4YfrpYIuQDiJ2TSAtu
vRyEezhbHwuGKXbK3L_mQfUnSRY8LRjyLEDbwAoMra_ohSfbYbNRijc2bn7UgsMpPRFXAYYIVVc-dSMQtLP4l6XhEPVTRiygV8qYjkmGvwPy4UtB3ZQXQ_Zo
VTlb-_RyLwrsqGlapPSde6sN-BJy1m
}

