sprite $Terminal_server [61x21/16z] {
pT1LWiKW341H80Aail_bJcIiBb_lrkLKI5PkuvjcnqsWF8ycjxtavq6TtbjI_DgoufUMMN6JDxQGuwao_SHtgyo12SegM4HCc_xXR1roHDZ45_YZtop3ZJTp
NKRnvZwKQqnzLSEmEIakH0HWAs9RcAvml3SvhhKYwWfqiO_a1SOkong63Gm0nLVW8ImnqZ84jzeiZK-hTNjAmYPiGtsQZLM4y_GqVM_q1G
}

