sprite $Terminal_server [96x33/16z] {
xTA53eGm383XQGNh-x_jiOQKSrbspX_1Fs2RiqYUq6Gy2qBpM5OUVFC2orDvO7agh_xpUFMVo2y-FObN_ucy-a_arNyYhxxq-7XyupBi-HHZ3ALuVn2lHiU-
_TUPpWDNumh_QT__lUEpZGzEmzE-N_dHL_gvkrGgll6kqgUEpzVduXl_9D_unSyubtmg6mXwb0Fefj9NtdmePPzr6s1_K-CRRpxDpNxPOD0Z2AYRypxstVdw
L7pZtLFMf_BcNw_2vvLt8ZBnetNNhyhAkvHPe6sJybOMRjh2MqdQTiZl
}

