sprite $Town [96x72/16z] {
xTK7ieGe58LXuIQGSFQ_su6EAdPypyd_0hvhKQUwfvzbPJgq33sITq0zqbSao87-348-qA_99V1XFC6S8Xtc1v2J17-KNufpR9WFMsTqZZJ37RLEwNv0E6gT
pdclMd2CZtJs8-m8dc7ETrzhFMYTtHVL6NBCEdsBLRMMOzRPVMh-39xUoEjUxl4whxv1t-09kuLfjmJVe-RBwE_pCGp5HpwIk_WY0VeE7tJ8oWEVOMUUHBJx
N_AFV0EvSwBl-AWcGrP-o_V8OMp-HJ_z8_t_VN-ixu_r_R6-FzRtn_h-xWTkqU_w_kORpXNvpjSyL9U-1kk5YkA-y0srdCgBab_uJATu1d_k6x9trwPhRkbB
rptHDpwGdNlFj_IPdxjVetlF9miV-gKrarz7ddh-cfuIOGkV-gdvOMgvTPrT-zOAN_eZF_gzs7tvmX_uqPTM7mIGzKF_1KyddbkXDMS0qGzyUko_uEcsdzke
WNbz8G1l-YD_yjctmhLOW73NgQ04spJu-_pLTwrmBpQIBhm0KPLf5OkT_Iml-BFVeR0iuJ8bHJLLeNLCRDtF9YzuqcjXLQpGnZDAuvK7_kHdCtd1axIqPyC1
dgQApYkjOsQo46PR-2E_ZbbiVG1rKaGTFvyQJsgdv4sUc4Z2gWJDjHlAs-Zk-zrennSEwv1hEVaqTlMPjktpnC9RlrIyydKSbjgfaQVHptNl3HO-x_2Xfxog
yuDVio7k-FxcZyFIYo-qJcZmPvX3xRvRrttUVNtHgpzCRl1ZXPi4PTTdEoMRzExxTOCV2-Jqsrc2JElScG_X1twi25FFK7NhyybuwfDRnutNvTl3BfhKOiBB
nC8vuqrF_2KV2ohVFtS6SjZBQDF2dzRndOyPcDsqY3AGuuxlDztuqTV5_sEcQHCdeARushTmJcMTXLvC5KXT7_AX3YVKRUhym-RSXU2dHt6i0ChzXawR7l5n
JWL0ZJmzZooXLNEQ-nNTj4_dYbOocjwAR2xerPBJFCSOzjWuDxXKzCeysAyY3QdWKgsrBAgrub99GMdwEaUYrb-Wc_TR_VLCXTpqeZy
}

