sprite $Town [61x46/16z] {
xTL7jgim381XrEKYzh_S1muwwFOSnkyVfNqkIS3RctNTdhVFvvRdbCVOtVjJ2vCbw26cGEhj8TOEP87Fy5107VvqouZg0K-m34GKdVRiXu8J-_XXQXir-Rfg
PDM9trgFvfwrQ5iD9o4IYtsFBLplsju-_r00I3zWsQtQ-8IjmH7fzrZ3I-F2_p4-nWY8pp4k76ucy3Vc-iA5jH_DoNzXZUPtSc4c8kxj3nnJOBMje60Pl-8P
qHXgUCQgmYp-5nxqqILMC_yRurPruhC3XqB5zWL_iRbiypOYd9A2x_C7N2mTc8dCZ_eCXpo6J3MpYgizCG6ehrfCFcrq5SgOpUSq_6efbttf4RnHD5M-BQiF
L_nYrviYegcz1xMXAbIncIsCnTwnU3PRkAdm7IrCDqYRcClKkvinbKvSb_BfUSNxw6Q4sOMhDNUhAxln619k11ao7xPiGnScp0fk8Pk7Lsn7Afd-Z5luEcaK
CphVAJFB2oDap9e_irq7w6nsvITcoWxiHxXbB8lsc7aMWiqOpJrZp5ZDZyflyPfr6fH3L7eSllcA8EDbIwsFY2v9CzGUUupUtALELE6CFRhYzbr0siQCY3dw
MMlzrRXUROgm_HQIgAynzbTBkGfzdV4V
}

