sprite $WAN [96x72/16z] {
nTO9QWCn44HH_ViVEdiA9WfDVwJ6vTqklzcHrfK0QovyPvY7OHu6-UytOxuuo0P--Ek6JzOrUVm6DtR6mzuB1tnI-TpmiyF50WnVTvpRyNb6hlJVjmLkV4YA
auF_ulSu02tT-qbHqNxZRrpskpgKPc_rmIxWyUi1Byw40Nx6n_b87-VpQXyqZwnh7rctFCYwEZVJztwtUEfxVkLPxy-efR_oRFrL1DAXIihbI6W6nTq_6FRt
LTevfxlZl_4Uxn-UupLFp_Ez5QSwk4xlTgIUD3jIJzpLO7MsZlOzxtqry7d_U9pFxvA7VkdHrzCpcZv87bYmp2f8tayrPlnzFE0gls6tVQ5PFXdcrnIVJEd9
b9vCqKbAGtw2PmMl_B22zxxDB9-jTRmFDIjmEys_bOs_7SlxQDtd17y7
}

