sprite $WAN [61x46/16z] {
dTC54WKX38FX_FS_z7Fjb0QIqPLl1L8T150Qo3Na-WL9t0TpmbI_5k3WDr75xDlkxAo-xw2u6VDC_Jl0w_uMIhnbQUchQsoBwJ9SJ6t5J9WPSuvncF4YiuK0
3vzbFqpwsiFlMbHEFVvLZTKaTefUPrFUkZfAApjKqTcT9aeJhHOy7aRBOlQnAdObh1ZvuPowQQoT2W4wj3B0O6KsrlfD02EjLPmZnp99h2rtfLuRORIoRD8h
}

