sprite $Workstation [62x64/16z] {
hTQBZgiw38NXnlQoGw4zx_-s9qvW82gOfjg_j4RNJsxdLXvRiWptUc-OPkFHi6bUD8r6zbhnRECOhYlM7x2w_XatJRzXrpzVRZejaup6q5NBZE6oxbfuCFct
McuBj43tq2LTvrgxBZd7-XwVQp2TneS2dHw7qXfjtUe0ZznE5rXY7H-EzGqM2VMftN6WuJey76eWHOVlzIKMkT3lNLFqgZqWk4qtXr4qTNfwTZey_AaN_6aX
jm7-qBPGfw-iu4m_fyT1XuSzxVN29veliT9Hs_BOTEdkiCOwnZUQOtklOnnhZd6i8tkl0pokM-YAzHuTItzTQHxeG_EupflsXlMSXxK0aAgVCwKqhgLgMvPv
_ksPQTB2uS_8icZDh7xD-aMJUc9-MseAAK7bY-e9gEjtLhESf-nDK_xCkdAfOjUwC9KOMZBlz156Me2seAuBJYrYT4IwK5FTiUltP2DfAslJB_1PT5hQqaqh
0CksXkyUDctLRx_z_6_j9VnDqdJURayvroa0XIU0YAw3T6lQ5lFtBGnbLX_QJ8YDouX4oz06IScN6jP7qI8iHGhMYOy8N4PjqiP2YTcrOtiKBM9oVA9opCH2
n7mO-H9HyhNBhdbDKBM1OKnG8aMP49cFowY-RkLKBxjMx6r_9ohT06Q8RtjhkM3l_HfgQRqAzlu7
}

