sprite $Workstation [96x99/16z] {
xTY9SgmW48LXWMRNuVtVzagBmpZ8n9EIk_zLwTg_TBLcdOxfT6-FTpxQEulfdHUt5j9GteGqb6T_77_mQG3F_Z2U_Q4y-uMN0tZsX_7i3-JP7ygpBzDYxaoP
ew-JqNVc6v_KdVsU_d-VzAMeqzU-EK-VTACFw82Fye2FwwGk-oIQv6a74l2dixgVxXPV83pk0phW0ykZFiuJukEt8SJ7boV4nvV7V7Xvt6-Nx_EWhmcx3UXh
JV1jE2cl-9fzO7dCr-n3o-C-zc0vhVLr7x-D_k3FI-EZjz6V_6GR7r--xuSa6nzVlkylyzJuyF9ztoRJ-FZoVJyaSUPBZE_xZpWrFdoRlc-JFl7nvLVgr8zf
QdryUTFpb_dT9o9yUVR5cH_VV3hu5vVdn1K_fw3R68vz2VZ0RM0VUx2u3o-F-y3ok8yzMDo7ReFxs6rm7riUzx7bSP_KQV8iKSFthtLbt5TV9Rkf2xwwexwl
nlhgPjydEz9tAKwt-df5wUdRj4mZ_IKjyrgump_-eHhO3zoSig_fpeBP8Yb4OD-xFHzTAGJtpQBPKyt_Fychah7gcmLJ8ZFK9xFxblQqfv9nzCr2vOkVGZwz
3sinVvmLklbQoBd2Lp-ABKccP4lclUw_AXMHDZKonMU-9Wdwv-V-tclzjeRP_SetduAhRbFtvoNpnKyFVzBXhd3HlFWU_w7L9WwvlycFbfiVX-hRYMVzgnya
5zEXkZIUglwg1il5-L2pFvAhwxkN-riwduRacb4Vfj1Ah6rJkCfFcvyTRzLpkjTfCjERjipiyYn-uJUVlz9r8BLFAbDjSnNQgVnXhgxoilhCRpwjVVc6ykWb
v2PNd_dTLzvJ_IaDwnlEi_WxN-yZ2w-DvZ_2zlCRdsdZiwAxSqLVJkGgppxN-1Jp39JzGFBZB0-tJCTyzJlHzlfaNrcPwyvCc-ShwfWlVdH0zb9pyjFU8mt8
JSz-
}

